//////////////////////////////////////////////////////////////////////////////
// ヘッダ名= 共通定数ヘッダ
// 日付      = 97/07/04
// ＶＲＴ  = 01-01-01-02
//         =             97/10/01 小岛（应ソ２Ｇ）修正
//         =             97/11/21 高岛（应ソ３Ｇ）修正
//         =             97/11/29 山田（ソ１Ｇ）修正
//
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-00-00,97/12/02,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-01-00,97/12/04,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-02-00,97/12/08,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-03-00,97/12/09,伊藤(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-04-00,97/12/16,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-05-00,97/12/17,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-06-00,97/12/25,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-07-00,98/02/04,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-08-00,98/02/26,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-09-00,98/03/27,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-10-00,98/04/03,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-11-00,98/04/27,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-12-00,98/07/07,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-13-00,98/07/15,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-14-00,98/08/20,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-15-00,98/08/21,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-16-00,98/09/02,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(NT),01-00-17-00,98/09/07,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-18-00,98/09/10,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(NT),01-00-19-00,98/09/22,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-20-00,98/09/29,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-21-00,98/10/19,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-22-00,98/10/28,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-23-00,99/03/01,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-24-00,99/03/19,高岛(应ソ３Ｇ)
// HISTORY = KS_PRMSTD(win3.1,NT),01-00-25-00,99/04/07,坂并田(ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-26-00,99/04/08,坂并田(ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-27-00,99/05/07,坂并田(ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-28-00,99/05/08,坂并田(ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-29-00,99/05/25,　　  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-30-00,99/05/31,　　  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-31-00,99/06/23,上ノ园(ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-32-00,99/07/28,坂并田(ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-33-00,99/08/11,加藤  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-34-00,99/09/08,加藤  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-35-00,99/09/22,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-36-00,99/09/24,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-37-00,99/09/28,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-38-00,99/10/05,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-39-00,99/10/12,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-40-00,99/10/28,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-41-00,99/11/04,坂并田(ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-42-00,99/11/06,坂并田(ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-43-00,99/11/08,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-44-00,99/11/18,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-45-00,99/11/24,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-46-00,99/11/26,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-47-00,99/11/29,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-48-00,99/12/14,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-49-00,99/12/24,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-50-00,99/12/27,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-51-00,00/01/13,藤木  (ソ２Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-52-00,00/01/27,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-53-00,00/02/01,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-54-00,00/02/02,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-55-00,00/02/16,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-56-00,00/03/06,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-57-00,00/03/13,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-58-00,00/03/29,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-59-00,00/04/17,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-60-00,00/05/08,平田  (ソ括Ｇ)
// HISTORY = KS_PRMSTD(NT       ),01-00-61-00,00/05/08,平田  (ソ括Ｇ)
// HISTORY = CSTV3,03-00-00-00,01/11/21,BHH(TianCZ) CST20009
// HISTORY = ICBV4,04-00-00-00,03/05/09,BHH(TianCZ) ICB40015
// HISTORY = 2002/01/23 : CST04000000 : IC Card Supported    //ICCard-CSTV4
// HISTORY = ICBV5,05-00-00-00,03/08/05,BHH(Sihaitao)   ICB50006
// HISTORY = CSTV7,07-00-00-00,04/07/30,BHH(Sihaitao)   CST70004
// HISTORY = CSTV7,07-00-00-00,04/08/02,BHH(Guopeng)    CST70014
// HISTORY = CIFTEE,09-00-00-00,04/08/05,Hashimoto      CIF00001
// HISTORY = CSTV7,07-00-00-00,04/08/11,BHH(Guopeng)    CST70022
// HISTORY = ICBV6,30-00-00-00,04/12/16,BHH(ChangMing)  CST70137
// History = BSCRDICB,30-00-01-00,05/03/08,BHH(Guopeng) CST70423
// History = 2006/01/06 ICB30-02-00-00 ICB62308 BHH(LNH)
// HISTORY = ICBV63,30-03-00-00,06/06/15,BHH(Lihl)      ICB63004
// HISTORY = GST,01-00-00-00,07/02/11,BHH(Liys)         CK#0396
// HISTORY = BSCRDGST,01-00-00-00,07/02/13,BHH(SunCQ)   GST10014
// HISTORY = BSCRDGST,01-00-00-00,07/02/26,BHH(SunCQ)   GST10021
// History = BSKYOGST,01-00-00-00,  2007/03/02 BHH(ZhouBo):   GST10020
// History = BSGNKGST,01-00-00-00,  2007/03/02,BHH(SZJ)   :   GST10017
// History = BSGNKGST,01-00-00-00,  2007/03/05,BHH(WuXiaowei) :   GST10005
// History = ESUNYGST,01-00-00-00,  2007/03/06,BHH(Guofy) :   GST10029
// History = BSGNKGST,01-00-00-00,  2007/03/07,BHH(SZJ)   :   GST10017(PG#00049)
// History = BSGNKGST,01-00-00-00,  2007/03/09,BHH(SZJ)   :   GST10017(PG#00081)
// History = BSGNKGST,01-00-00-00,  2007/05/24,BHH(WuXiaowei) :   GST10380
// History = BSGNKGST,01-00-00-00,  2007/05/25,BHH(WuXiaowei) :   GST10383
// History = SYSMGGST,10-10-10-00,  2007/07/23 BHH(Liwei):    GV101028
// HISTORY = BSCRDGST,10-10-10-00,07/08/07,BHH(XINGZN)              //GV101004
// History = BSGNKGST 10-10-10-00,2007/08/15  BHH(XINGZN)   GV101001
// History = BSVDMGST 10-11-00-00,2007/09/28  BHH(LIYS)     GV110003
// History = SYSMGGST,10-12-00-00,07/11/12,   BHH(Guofy)    GV120002
// History = HWBRM, 13-00-04-00,  2007/11/15,BHH(Xuxiaoming)  :   13-00-04-07
// History = HWBRM, 13-00-07-00,  2008/03/10,BHH(Xuxiaoming)  :   13-00-07-02
// History = DRASGST,13-00-07-00, 2008/03/14,BHH(YUC)  :   13-00-07-04
// History = HWBCR, 30-00-00-00,  2009/12/19,BHH(huangyc)  : 30-00-00-11
// History = DRASSTD,10-00-00-00, 2010/03/15,BHH(ZHUQJ)    : STD00029(PG#00120)
// History = HWBRM, 40-01-07-00,  2012/05/10,
// History = HWBRM, 40-01-08-02,  2012/06/12,
// History = HWBRM, 40-01-08-A3,  2012/06/21,
//////////////////////////////////////////////////////////////////////////////

#ifndef _BS_PRM_H_  //96.4.23  M.Hiroya
#define _BS_PRM_H_  //96.4.23  M.Hiroya

#pragma  warning ( disable : 4010 )
#pragma  warning ( disable : 4100 )
#pragma  warning ( disable : 4244 )

// ＡＴＯＭ　追加定数定义(开始) //////////////////////////////////////////////
/* 共通ｒｅｔｕｒｎ情报 */
#define NODATA          2   // デ－タ无しによる终了 96.04.08 冈本

//CDM 与 CIM 标示
#define     CDM     1                                                           //GST10017
#define     CIM     2                                                           //GST10017

/* 情报初期化用引数 */
#define INFO_RESET      1   // 初期复旧时の情报／デ－タ初期化
#define INFO_KOUTAI     2   // 客交代时の　情报／デ－タ初期化
#define INFO_RENTORI    3   // 连续取引时の情报／デ－タ初期化

#define ST_JNL_MAISUU     71    // 电子ジャ－ナル印字枚数情报 96.03.15 桑
#define ST_EMBOSS_MAISUU  72    // エンボス印字枚数情报 96.03.15 桑
#define ST_YOUSHI2        73    // 明细票用纸状态2 96.07.03 桑
#define ST_UNIT2          75    // 96.08.02 藤原
#define ST_BAITAI2        76    // 96.08.02 藤原

// 情报取得项目ＩＤ
#define DV_PBM_VRT        0     // ＰＢＭ デバイスバ－ジョン情报      //WOSA
#define DV_SPR_VRT        1     // ＳＰＲ デバイスバ－ジョン情报      //WOSA
#define DV_BRM_VRT        2     // ＢＲＭ デバイスバ－ジョン情报      //WOSA
#define DV_MCU_VRT        4     // ＭＣＵ デバイスバ－ジョン情报      //WOSA
#define DV_JPR_VRT        5     // ＪＰＲ デバイスバ－ジョン情报      //WOSA
//ICB50026 #define DV_EBD_VRT        6     // ＥＢＤ デバイスバ－ジョン情报      //WOSA
//ICB50026 #define DV_FLC_VRT        7     // ＦＬＣ デバイスバ－ジョン情报      //WOSA
#define EP_PBM_VRT        8     // ＰＢＭ ＥＰバ－ジョン情报          //WOSA
#define EP_BRM_VRT        9     // ＢＲＭ ＥＰバ－ジョン情报          //WOSA
#define EP_MCU_VRT        11    // ＭＣＵ ＥＰバ－ジョン情报          //WOSA
#define EP_PBM_SENSOR     12    // ＰＢＭ センサ情报                  //WOSA
#define EP_BRM_SENSOR     14    // ＢＲＭ センサ情报                  //WOSA
#define EP_MCU_SENSOR     16    // ＭＣＵ センサ情报                  //WOSA
#define EP_JPR_VRT        18    // ＪＰＲ ＥＰバ－ジョン情报          //WOSA 98.09.22 小规模ATM对应
#define DV_IMP_VRT        19  //(IMPRハ＂—シ＂ョン情报)   NEW 99/09/22 三和
#define EP_IMP_SENSOR     20  //(センサ情报)   NEW 99/09/22 三和
#define EP_IMP_VRT        21  //(EPハ＂—シ＂ョン情报)   NEW 99/09/22 三和
#define EP_SPR_VRT        22    //ＳＰＲ ＥＰバ－ジョン情报             // 2000/02/01 LAK-45
#define DV_PIN_VRT        23    //ＰＩＮ Device 情报
#define EP_PIN_VRT        24    //ICB50016
#define EP_MCU_3Q8        25    //ICB50026
#define EP_MCU_PRS        26    //ICB50026
#define EP_MCU_SPCA       27    //ICB50026
#define EP_MCU_UPCA       28    //ICB50026
#define EP_MCU_EMVC       29    //ICB50026
#define EP_MCU_ICCC       30    //ICB50026
#define EP_SIU_VRT        31    //ICB50025
#define DV_SIU_VRT        32    //ICB50025
#define EP_CAM_VRT        33    //ICB50044
#define DV_CAM_VRT        34    //ICB50044
#define DRV_SIU_VRT       35    //CST70137
#define DRV_SPR_VRT       36    //CST70137
#define DV_ENC_VRT        37    //GST10019
#define SPR_LAMP_STATUS   38    //ADM2SPR点灯情报                               //GST10380

#define VERSIONSIZE     16  // バ－ジョンサイズ
//#ifdef WINSP
//#include "smem.h"           //共有メモリアクセスマクロ关数用ヘッダ    96/4/14
//#include "ksmacro.h"        //共通マクロ用ヘッダ(RETURNマクロなど)    96/4/14
//#else
//#include "KSDLL/SMEM.H"
//#include "KSMACRO.H"

#endif
// ＡＴＯＭ　追加定数定义(终了) //////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////
////////////////////// 以降は新／旧ミドルの定数定义 //////////////////////////
//////////////////////////////////////////////////////////////////////////////
// 新／旧ミドルの定数定义の内、管理元オブジェクトの明确なものは、自オブジェ //
// クトの”xxxxxprm.h”ファイルに移设すること。この际以下のようなコメントを //
// 记述しておくこと。                                                        //
// 「ＩＮＪＩ＿ＸＸＸＸは、ｕｓｐｒｔｐｒｍ　ｈに移设。９６.０３.１３名前」 //
//////////////////////////////////////////////////////////////////////////////

/*　共通引き数    */
#define ON      1      //
#define OFF     0      //
#define NOEVNT      2      //

/*  リトライ要求    */
#define RETRY_OFF 0 //リトライ不要              //CST00001
#define RETRY_ON  1 //リトライ要                //CST00001

/*  回线断种类  */
#define SOCKET_DAN 0    //SOCKET断              //CST00001
#define HOST_DAN   1    //HOST断                //CST00001


/*  共通ｒｅｔｕｒｎ情报    */
#define OK              1
#define NG              0
#define JunOK           2   //准正常    ICB40015
#define ACC             1
#define NACC            0
#define BUFSHORT        6   //共通用  バッファが短い  96.04.23 山森
#define SRAM_JUNSEIJOU1     2       //SRAM准正常1
#define SRAM_JUNSEIJOU2     3       //SRAM准正常2
#define SRAM_ERROR1     4       //SRAM异常1
#define SRAM_ERROR2     5       //SRAM异常1
#define SRAM_ERROR3     6       //SRAM异常1
#define SRAM_NO_EFFECT  7       //SRAM未サポ－ト
#define EYEMODE_JUN_OK    2   //视觉障害者用准正常  //IOC-01000400  97/09/17 第三
#define EYEMODE_NONSTOPVG   3       //视觉障害者用中断禁止カ＂イタ＂ンス  //IOC-01000400  97/09/29 第三

#define REBOOT_NEED     8       //VDM异常重启要     //GST10029
#define REBOOT_NOTNEED  9       //VDM异常重启不要   //GST10029

/* BRM UNIT 类型
#define BRMUNITTYPE_INCORPORATE     1       //CST20009  一体化类型
#define BRMUNITTYPE_SEPERATE        0       //CST20009  分割类型
*/

/*  ＡＴＭ共通情报     */
#define AUTO        0
#define SPL     1
#define MTPL        2
#define OPL     3
#define HOST        4
#define CCMS        5
#define ADC     6
#define ASS     7      //ASS  98/02/26 野村证券
#define WEB     8       //フ＂ラウサ＂ 99/11/29 ネットフュ—チャ—
#define TTU     9       //GV110003
#define SOFTTTU     10      //GV120002

#define SHIHEI          1
#define KOUKA           2
#define TORICARD        3
#define FURICARD        4
#define MEISAI          5
#define PB          6
#define TP          7
#define RESERVE           2
#define REMANET          3
#define HOJYU           4
#define REMAININSUFFICIENT       5
#define NEEDSUPPLY        6
#define SETNOTGOOD        7
#define CANCEL_END      8
#define FORCE_BRING        9
#define JAM            10
#define DOUBLE_IN       11
#define KAISYU_FULL     12
#define WT_ERR          13
#define READ_ERR        14
#define CHECK_ERR       15
#define IMR_ERR         16
#define MAX_INJI_ERR        17
#define PAGE_NG         18
#define EP_DOWN         19
#define LP_DOWN         20
#define FULL          21
#define WASURE          22
#define KAISYU          23
#define MS_NO        24
#define MEKURI_ERR      25
#define IKKATSU_ERR     26
#define KURIDASHI_ERR       27
#define KURIDASHI_2MAI      28
#define SET_MISS        29
#define TAIHI_KATA      30
#define ORITATAMI       31
#define CSM_MANPAI      32
#define RJB_MANPAI      33
#define SHIHEI_NASHI        34
#define OVERLOAD       35
#define SHEETS_OVER     36
#define TAKEOUT_MISS       37
#define ECHO_ERR        38
#define SAIKAN_YOU      39
#define RJ_EXIST          40
#define LENGTH_ERR      41
#define CARD_LENGTH_ERR 42          // カード長さ異常　2004/03/01
#define CARD_NO      43
#define MCRW_ERR        44
#define CEASE          45
#define OPERATION           46
#define JIKOU           47
#define OTHERBANK           48
#define NOT_MANPAI      49
#define SUMI            50
#define NOT_SUMI        51
#define ZERO            52
#define NOT_ZERO        53
#define YOUSHI_ERR      54
#define TATAMI_ERR      55
#define RJ_ARI_OVER     56
#define IBUTSU          57
#define SYOKEIKA        58
#define HANBETSU_FUNOU      59
#define CHECK_MISS      60
#define RTN_NO       61
#define YOUSHI          62
#define UNIT            64
#define PRTHEAD         65
#define RIBON           66
#define TCM_HAKKOU      67
#define PB_HAKKOU       68
#define TP_HAKKOU       69
#define MC_YUKO_ZERO        70
#define MC_YUKO_UP      71
#define EMBOSS_NO        72
#define MAN         73
#define GOSEN           74
#define SEN         75
#define SONKEN          76
#define GOHYAKU         77
#define HYAKU           78
#define GOJU            79
#define JU          80
#define GO          81
#define ITI         82
#define SOTENKO         83
#define SOTENRJKO       84
#define RJKO            85
#define KAISHU          86
#define IRIGUCHI        87
#define SHUTTER         88
#define COIN            89
#define SOTENKOSET      90
#define RJKOSET         91
#define NUKITORIIJYO        92
#define KYOSEIKAI       93
#define COINTSUKAARI        94
#define COINTSUKANASHI      95
#define OVERKO          96
#define NEARMANPAI      97
#define MAKITORI_TM_OUT     98
#define CA_KAKUNIN      99
#define ETC         100
#define MSBC_ERR        101
#define BC_ERR          102
#define ZENGYOUINJI_PAGE        103
#define HAKUSHI_PAGE      104
#define HALT1          105
#define RELEASE          106
#define HAKKOUKYUSHI        107
#define HAKKOUKAIJYO        108
#define RESET_NG        109
#define STOCK           110
#define BUNRI_NG        111
#define TANDOKU_OUT     112
#define MC_ZERO         113
#define JITEN           114
#define TATEN           115
#define MAE_HAKKOU      116
#define MAE_HAKKOU2     117
#define USHIRO_HAKKOU       118
#define USHIRO_HAKKOU2      119
#define MAE_HAKKOUSET       120
#define MAE_HAKKOU2SET      121
#define USHIRO_HAKKOUSET    122
#define USHIRO_HAKKOU2SET   123
#define SHUTTERSW       124
#define COINTSUMARI     125
#define KYOSEI          126
#define NINI            127
#define MAN_OK          128
#define SEN_OK          129
#define TCM_KAIJYO      130
#define TCM_SYUKUTAI        131
#define BILLDOUSA       132
#define COINDOUSA       133
#define KKAISYU         134
#define TOCHUU          135
#define KINGAKU_OVER        136
#define SHU_UNIT        137
#define MCTCM           138
#define TCMMC           139
#define MCNASHI         140
#define TCMNASHI        141
#define NASHIMC         142
#define NASHITCM        143
#define HUMEI           144
#define JPR_UNIT        145
#define OVRBX_MANPAI        146
#define CST_MANPAI      147
#define RJBS_MANPAI     148
#define RJBK_MANPAI     149
#define RB_MANPAI       150
#define RJSD_MANPAI     151
#define NO_DOWN         152
#define CST_FUTA        153
#define CHECK_NASHI     154
#define CSTJUNBI        155
#define RJKO_OK         156
#define CARD_MC         157
#define CARD_TCM        158
#define MAETOBIRA       159         // 前搬送路(前扉) WBRM  2000/02/02 ATOM-NT
#define NISEN           160         //ICB00025  2001/07/25
#define BOX_MISSFEED    161         //CST20213
#define MARK_NG         162         //CSTV4
#define RETRACTBOX          163     //CSTV4
#define RB5CASH_ARI		164                                 //STD40-02-01-02(FS#00017)
#define RIBBONTHIN          400     //CST30014


#define ENDPAGE_INJI_ERR    164
#define UKETSUKE_ERR        165
#define INDICATE_COLLECT    166     //中央指示卡回收                            //CST70022
#define TAIHI_JYAM      168
#define END_CODE_NOT        169
#define VT_PARITY_ERR       170
#define HZ_PARITY_ERR       171
#define STR_CODE_NOT        172
#define READ_KYUSHI     173
#define READ_KAIJYO     174
#define HANSOURO            175
#define TAIHIRO             176
#define HANSOUROANDTAIHIRO  177
#define LINE_NG             178
#define BLINK           179
#define BIF_ACCESS_NG       180
#define RIBONSET            181
#define NEW_ARI            185      // 新通帐有り(96.08.21 千叶)
#define OLD_ARI            186      // 旧通帐有り(96.08.21 千叶)
#define HYOURI_NG          187      // 表里チェックＮＧ
#define TP_ARI             188      // 单票有り
#define PB_ARI             189      // 通帐有り(假96.12.04 水谷)
#define FRB_ZANRYU         190      // ＦＲＢ残留(97.06.25 森田)
#define UESHUTTERSW        191      // 上侧シャッタ开(97.06.09 中野)
#define TOUNYU_MANPAI      192      // 投入口シ＂ャム(97.06.09 中野)
#define HEI_MISS           193      // 强制シャッタ闭ミス(97.07.03 中野)
#define RESERVE_ERR          194      // 保留障害(97.10.01 ＳＢＫ)
#define TSUTSU_MANPAI      195      // 收纳筒满杯(97.10.02 山田TS)  97/11/28 小规模
#define SEN_MANPAI         196      // 千元满杯(97.10.13 原TS)    97/11/28 小规模
#define IDOURJB_MANPAI     197      // 移动用リシ＂ェクトホ＂ックス满杯(97.12.04 ＬＡＫ)     // 小规模
#define EXUNIT_SET         198      // 扩张ホッパユニットセット状态     98/08/20  ミドル
#define EXHOPPER_SET       199      // 扩张ホッパホッパセット状态       98/08/20  ミドル
#define EXHOPPERA1_HAKKOU       200     // 扩张ホッパＡ１媒体状态   98.08.21 NSB
#define EXHOPPERA2_HAKKOU       201     // 扩张ホッパＡ２媒体状态   98.08.21 NSB
#define EXHOPPERA3_HAKKOU       202     // 扩张ホッパＡ３媒体状态   98.08.21 NSB
#define EXHOPPERA4_HAKKOU       203     // 扩张ホッパＡ４媒体状态   98.08.21 NSB
#define EXHOPPERA1_HAKKOUSET    204     // 扩张ホッパＡ１セット状态 98.08.21 NSB
#define EXHOPPERA2_HAKKOUSET    205     // 扩张ホッパＡ２セット状态 98.08.21 NSB
#define EXHOPPERA3_HAKKOUSET    206     // 扩张ホッパＡ３セット状态 98.08.21 NSB
#define EXHOPPERA4_HAKKOUSET    207     // 扩张ホッパＡ４セット状态 98.08.21 NSB
#define KCSTSET                 208   // 回收カセットセット状态  98.09.07 小规模
#define KCST                    209   // 回收カセット媒体有无 98.09.07 小规模
#define KCSTJ                   210   // 回收カセット状态     98.09.07 小规模
#define KCSTCNT                 211   // 回收カセット媒体枚数 98.09.07 小规模
#define KAISHUKOSET             212   // 回收库セット状态    99/04/08 TBK（ＭＣＤ）
#define KAISHUKO                KAISHU// 回收库(现状KAISHUを回收库として使用していたが分かりやすくする）99/04/08 TBK（ＭＣＤ）
#define CST1SET                 213   // 纸币カセット1セット状态 99/04/08 TBK（ＭＣＤ）
#define CST2SET                 214   // 纸币カセット2セット状态 99/04/08 TBK（ＭＣＤ）
#define CST3SET                 215   // 纸币カセット3セット状态 99/04/08 TBK（ＭＣＤ）
#define MANCST                  216   // 纸币万元カセット     99/04/08 TBK（ＭＣＤ）
#define SENCST                  217   // 纸币千元カセット     99/04/08 TBK（ＭＣＤ）
#define OVERKOSET               218   // 予备カセット セット     99/09/03 ＦＢＫ对应 GCOM1支援
#define TSUTSUSET               219   // 筒 セット           99/09/03 ＦＢＫ对应 GCOM1支援

#define MISAPOTO        220    //(未サポ－ト)   NEW 99/09/22 三和
#define INK         221    //(出纳印インク)   NEW 99/09/22 三和
#define MICRRIBON       222    //(MICRリホ＂ン)   NEW 99/09/22 三和
#define KOUKINKAISHU        223    //(公金回收)   NEW 99/09/22 三和
#define TEGATAKOGITTEKAISHU1    224    //(手形·小切手回收1)   NEW 99/09/22 三和
#define TEGATAKOGITTEKAISHU2    225    //(手形·小切手回收2)   NEW 99/09/22 三和

#define MICR_NASHI                226   //手形·小切手にMICRが无い   NEW 99/09/22 三和
#define IMP_ERR           227   //ＩＭＰＲエラ－   NEW 99/09/22 三和
#define BA_RONRIMUKOU         228   //媒体论理无效   NEW 99/09/22 三和
#define BA_MUKOU          229   //媒体无效   NEW 99/09/22 三和
#define SEQUENCE          230   //デバイスにてシ－ケンスエラ－发生   NEW 99/09/22 三和
#define BA_NASHI          231   //媒体が见つからない   NEW 99/09/22 三和
#define FIELD_NASHI       232   //フィ—ルト＂が见つからない   NEW 99/09/22 三和
#define TWAIN             233   //TWAINソ—スの制御中、エラ—   NEW 99/09/22 三和
#define IIA_MEM           234   //iiA内部でメモリ不足が发生   NEW 99/09/22 三和
#define IIA_ERR           235   //iiA内部で予期しないエラ—が发生   NEW 99/09/22 三和
#define RECOGNIZE         236   //认识が失败   NEW 99/09/22 三和
#define ENGINE            237   //认识エンシ＂ン内でエラ—が发生   NEW 99/09/22 三和
#define FILESOUSA         238   //ファイル操作に失败   NEW 99/09/22 三和
#define MEDIASKEWED       239   //媒体がスキュ—した 99/09/22 三和
#define FORMNOT           240   //指定されたフォ—ム定义が见つからない 99/09/22 三和
#define KAISHUU_FUKA      241   //回收不可 99/10/05 三和
#define FUMEI             242   //不明 99/10/28 三和
#define WARNING           243   //回复可能なエラ－が发生した                  99/11/06 三和
#define ENGINE_WARNING    244   //认识エンジン内で回复可能なエラ－が发生した  99/11/06 三和
#define IIA_WARNING       245   //ｉｉＡ内部で回复可能なエラ－が发生した      99/11/06 三和
#define CHOUHYOU_WARNING  246   //帐票识别で回复可能なエラ－が发生した        99/11/06 三和
#define DENOMI_ERR        247   //STD40-00-00-00 UR
#define ESC_MANPAI        248   //STD40-00-00-00 UR
#define BILL_TRACE_FULL   249	//BILL TRACE DATA FULL			//STD40-00-06-01<Tracing> ADD

#define EXHOPPERB1_HAKKOU       247     // 扩张ホッパＢ１媒体状态   99/11/24 ATOM-NT
#define EXHOPPERB2_HAKKOU       248     // 扩张ホッパＢ２媒体状态   99/11/24 ATOM-NT
#define EXHOPPERB3_HAKKOU       249     // 扩张ホッパＢ３媒体状态   99/11/24 ATOM-NT
#define EXHOPPERB4_HAKKOU       250     // 扩张ホッパＢ４媒体状态   99/11/24 ATOM-NT
#define EXHOPPERB1_HAKKOUSET    251     // 扩张ホッパＢ１セット状态 99/11/24 ATOM-NT
#define EXHOPPERB2_HAKKOUSET    252     // 扩张ホッパＢ２セット状态 99/11/24 ATOM-NT
#define EXHOPPERB3_HAKKOUSET    253     // 扩张ホッパＢ３セット状态 99/11/24 ATOM-NT
#define EXHOPPERB4_HAKKOUSET    254     // 扩张ホッパＢ４セット状态 99/11/24 ATOM-NT
#define EXHOPPERC1_HAKKOU       255     // 扩张ホッパＣ１媒体状态   99/11/24 ATOM-NT
#define EXHOPPERC2_HAKKOU       256     // 扩张ホッパＣ２媒体状态   99/11/24 ATOM-NT
#define EXHOPPERC3_HAKKOU       257     // 扩张ホッパＣ３媒体状态   99/11/24 ATOM-NT
#define EXHOPPERC4_HAKKOU       258     // 扩张ホッパＣ４媒体状态   99/11/24 ATOM-NT
#define EXHOPPERC1_HAKKOUSET    259     // 扩张ホッパＣ１セット状态 99/11/24 ATOM-NT
#define EXHOPPERC2_HAKKOUSET    260     // 扩张ホッパＣ２セット状态 99/11/24 ATOM-NT
#define EXHOPPERC3_HAKKOUSET    261     // 扩张ホッパＣ３セット状态 99/11/24 ATOM-NT
#define EXHOPPERC4_HAKKOUSET    262     // 扩张ホッパＣ４セット状态 99/11/24 ATOM-NT

#define PBSKURIDASHI_ERR        263     //ＰＢＳ通帐缲出し异常        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define EXUNIT                  264     //扩张ユニット                99/11/26 TMBP 东京三菱ＡＰＩＭ

#define HOPPER0_HAKKOU          265     //扩张ホッパ０媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER1_HAKKOU          266     //扩张ホッパ１媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER2_HAKKOU          267     //扩张ホッパ２媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER3_HAKKOU          268     //扩张ホッパ３媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER4_HAKKOU          269     //扩张ホッパ４媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER5_HAKKOU          270     //扩张ホッパ５媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER6_HAKKOU          271     //扩张ホッパ６媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER7_HAKKOU          272     //扩张ホッパ７媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER8_HAKKOU          273     //扩张ホッパ８媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER9_HAKKOU          274     //扩张ホッパ９媒体状态        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER10_HAKKOU         275     //扩张ホッパ１０媒体状态      99/11/26 TMBP 东京三菱ＡＰＩＭ

#define HOPPER0_HAKKOUSET       276     //扩张ホッパ０セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER1_HAKKOUSET       277     //扩张ホッパ１セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER2_HAKKOUSET       278     //扩张ホッパ２セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER3_HAKKOUSET       279     //扩张ホッパ３セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER4_HAKKOUSET       280     //扩张ホッパ４セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER5_HAKKOUSET       281     //扩张ホッパ５セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER6_HAKKOUSET       282     //扩张ホッパ６セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER7_HAKKOUSET       283     //扩张ホッパ７セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER8_HAKKOUSET       284     //扩张ホッパ８セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER9_HAKKOUSET       285     //扩张ホッパ９セット状态      99/11/26 TMBP 东京三菱ＡＰＩＭ
#define HOPPER10_HAKKOUSET      286     //扩张ホッパ１０セット状态    99/11/26 TMBP 东京三菱ＡＰＩＭ

#define HORYUBU                 287     //一时保留部    2000/01/27 MR-ATM(SCOM)对应

#define MAETOBIRASET            288     //纸币前扉セット状态    2000/03/29 45LAK
#define USHIROTOBIRASET 289         // BRM后扉  WBRM  2001/04/16 ATOM-NT
#define USHIROTOBIRA    290         // BRM后扉  WBRM  2001/04/16 ATOM-NT

#define KYUUSHI                 291 //休止                                      //CST70022

#define CST4SET                 292   // 纸币カセット4セット状态                //GST10005
#define CST5SET                 293   // 纸币カセット5セット状态                //GST10005
#define CST6SET                 294   // 纸币カセット6セット状态                //GST10005
#define CST7SET                 295   // 纸币カセット7セット状态                //GST10005
#define CST8SET                 296   // 纸币カセット8セット状态                //GST10005
#define CST9SET                 297   // 纸币カセット9セット状态                //GST10005
#define CST10SET                298   // 纸币カセット10セット状态               //GST10005

//For Chinese BRM
#define CST100            301     //CST100                      //CST00001
#define CST50             302     //CST50                       //CST00001
#define CST10             303     //CST10                       //CST00001
#define CST20             304     //CST20                       //CST00001
#define BOX1              311     //BOX1                        //GST10005
#define BOX2              305     //BOX2                        //CST00001
#define BOX3              306     //BOX3                        //CST00001
#define BOX4              308     //BOX4                        //CST30021
#define BOX5              312     //BOX5                        //GST10005
#define BOX6              313     //BOX6                        //GST10005
#define BOX7              314     //BOX7                        //GST10005
#define BOX8              315     //BOX8                        //GST10005
#define BOX9              316     //BOX9                        //GST10005
#define BOX10             317     //BOX10                       //GST10005

#define LOWERUNIT         307     //下UNIT      UL291 2001/09/11

#define DJNL_HALT1        309     //电子日志休止        ICB40025
#define DJNL_RELEASE      310     //电子日志休止解除    ICB40025

#define RESENDBACK      318                                                     //GST10383
#define URJBDOOR        319     //URJBDOOR                      //GV101001
#define URJB            320     //URJB                          //GV101001

#define FINGERDETECTED  900     //バイオデータ認証／登録で指検知        //CIF00001
#define BIODATA_NG      901     //バイオデータ認証／登録でデータＮＧ    //CIF00001
#define WINDOW_ERROR    902     //CIF00001

//口座选择のために追加
#define PANFIX            0         //DEFAULT口座
#define PAN           1         //主な口座
#define SAN1              2         //サブ口座1
#define SAN2              3         //サブ口座2

#define EXIST     1
#define NO   0
#define FUTEI   2

#define SHINKEN 0
#define MOGIKEN 1

#define KAI 0
#define HEI 1
#define NOTSUPP 2                                                               //GST10017

#define NOTOPEN         2                                                       //GST10017(PG#00081)

#define TOBIRA_NASHI    0xffff

#define ICCARD_ERROR  161     //ICCard-CSTV4

//--< DKB ＡＰ要求案No.012 纳入仕样8-24,10-4 >--//

#define MANHOJYU    1
#define SENHOJYU    2
#define AUTOKAISYU  3
//----------------------------------------------//

#define BRM_OK  2
#define COM_OK  3

#define BIF_LD_START    0
#define BIF_LD_CONTINUE 1
#define BIF_LD_RETRY    2
#define BIF_LD_END      3

#define UNIT_BNASHI     0
#define UNIT_HAISYUTSU  1
#define UNIT_KAISYU     2
#define UNIT_HORYUU     3
#define UNIT_WASUREKAI  4
//有帐无帐付き取引名称

#define NONAME          0
#define PBHARAI         2
#define MCHARAI         1
#define PBAZUKE         4
#define MCAZUKE         3
#define MCZANSYO        6
#define PBKINYU         5
#define MCFURIKOMISYOKAI    7
#define PBFURIKOMISYOKAI    8
#define MCFURIKOMI      11
#define PBFURIKOMI      10
#define GENFURISYOKAI       12
#define PBFURIKOMIJIKKOU    11
#define MCFURIKOMIJIKKOU    10
#define GENFURIJIKKOU       13
#define CASING          14
#define CSZANSYO        15
#define TSUUBANSYOKAI       21
#define SEISASYOKAI     22
#define TEIKIAZUKESHOUKAI   21
#define TEIKIAZUKEJIKKOU    22
#define TEIKIFURIKAESHOUKAI 23
#define TEIKIFURIKAEJIKKOU  24
#define MCFURIKAE       25
#define PBFURIKAE       26
#define RYOUGAE         27
#define CREDIT          28
#define HENSAI          29
#define KASITUKE        30
#define KAIYAKU         31
#define PBNOMIHARAI     32
#define PBZANSYO        33
#define ICHIBUKAIYAKUSYOUKAI    37
#define BRMSOUTEN       51
#define COMSOUTEN       52
#define BRMKAISYU       53
#define COMKAISYU       54
#define BRMICHIBUK      55
#define B_AUTOS         56
#define C_AUTOS         58
#define BIFLOAD         60
#define BRMRJ           61
#define COMRJ           62
#define WASURE_KAISYU       63
#define BRMHOJYU        64
#define COMHOJYU        65
#define B_AUTOK         66
// #define C_AUTOK                     67          //硬货自动回收
#define COMBUBUNK       68
#define KAIKYOKU        69
#define HEIKYOKU        70
#define SYOKEI          71
#define GOKEI           72
#define BAUTOSRJ        73
#define CAUTOSRJ        74
#define BIFREV          75
#define PRGREV          76
#define SETTEI          77
#define CDKAIKYOKU      78
#define ERRCODE         79
#define ERRSYOSAI       80
#define ERRNAIYOU       81
#define DNSJNL_INJI     82
#define TOKUSYUMSG      83
#define USER_KOBETSU        84
#define KYUJITSU_CHK        85
#define BRMKYOSEISOUTEN     86
#define COMKYOSEISOUTEN     87
#define PBKURIKOSHI     88
#define RESET_KAISYU        89
#define AUTO_SEISA      90
#define B_AUTOS2        91
#define C_AUTOS2        92
#define AUTO_SEISA2     93

//取引名称(上と同じものはここにはなし)

#define MCSAKI          20
#define PAYMENT           16
#define DEPOSIT           17
#define MCZANSYO        6
#define PBKINYU         5
#define FURIKOMI        44
#define KOUZAFURISYOKAI     18
#define KOUZAFURIJIKKOU     19
#define FURIKAE         9
#define GENFURI         13
#define CASING          14
#define CSZANSYO        15

//取引キ－情报
#define HARAIKEY        502
#define AZUKEKEY        503
#define MCZANSYOKEY     504
#define PBKINYUKEY      505
#define FURIKOMIKEY     506
#define FURIKAEKEY      541
#define CASINGKEY       507
#define CSZANSYOKEY     508
#define HARAI1MANKEY        538
#define HARAI3MANKEY        539
#define HARAI5MANKEY        540
#define HARAI2MANKEY        545
#define HARAI10MANKEY       542
#define RYOUGAEKEY      543
#define TEIGAKUKEY      544


//ＡＴＭモ－ド
#define CHECK      17
#define DEMO        18

//有帐无帐识别
#define YUUCHOU     1
#define MUCHOU      2

//状态
#define FUKAKUTEI   1
#define KAKUTEI     2

//动作モ－ド情报
#define GENKOU      0x30
#define AD2     0x31

//カ－ド种类
#define NO           0
#define OLDMC           1
#define SHINMC          2
#define SHINSYSMC       3
#define SHINSYSPB       3

//通帐种类
#define NO           0
#define OLDPB           1
#define SHINPB          2
#define TU_SOUGOU_FU        3
#define TU_SOUGOU_TEI       4
#define TU_TOUZA        5
#define TU_TUUCHI       6
#define TU_CHOCHIKU     7
#define TU_TEIKI        8
#define TU_TSUMITEIKI       9
#define TU_TEIKITSUMI       10
#define TU_NOUZEI       11
#define TU_CARDLOAN     12
#define TU_JYUUGYOUIN       13
#define USER            14
#define TEIKI           15
#define KOUIN           16
#define FUTSUU          17

#define PBM_HOPPER      0
#define PBM_KAISYUBOX       1
#define TP_HOPPER       2
#define SPR_HOPPER      3
#define SPR_KAISYUBOX       4
#define TCM_HOPPER      5
#define JPR_HOPPER      6

#define BRM_BOX2        7
#define BRM_BOX3        8

#define BRM_RJBOX       9
#define BRM_KAISYUBOX       10
#define COM_500BOX      11
#define COM_100BOX      12
#define COM_50BOX       13
#define COM_10BOX       14
#define COM_5BOX        15
#define COM_1BOX        16
#define COM_RJBOX       17
#define COM_KAISYUBOX       18
#define JNL_SPOOL       19
#define MCU_KAISYUBOX       20
#define BRM_SOUTENRJBOX     21
#define COM_SOUTENRJBOX     22
#define COM_OVERFLOWBOX     23
#define TCM_RIBBON      24
#define BRM_BOX4      25    //CST30021

#define BRM_BOX1      26                                                        //GST10005
#define BRM_BOX5      27                                                        //GST10005
#define BRM_BOX6      28                                                        //GST10005
#define BRM_BOX7      29                                                        //GST10005
#define BRM_BOX8      30                                                        //GST10005
#define BRM_BOX9      31                                                        //GST10005
#define BRM_BOX10     32                                                        //GST10005
#define BRM_URJB      33      //URJB                                            //GV101001


/* by zj 2002/3/14
#define BRM_FRBBOX      25     //ＦＲＢＢＯＸ状态(常阳银行で设定)
#define BRM_CSTBOX      26     //カセットＢＯＸ状态(常阳银行で设定)  97/11/18
#define PBM_CASSETTE1   27     //カセット１ 99.04.07 SBK
#define PBM_CASSETTE2   28     //カセット２ 99.04.07 SBK
#define BRM_NYUUKINKOBOX    29 //入金ＢＯＸ状态  2000/05/08 FBK
//IMPR种类 99/0922 三和
#define IMP_KOUKINKAISHUUBOX             29  //公金回收ＢＯＸ 99/0922 三和
#define IMP_TEGATAKOGITTEKAISHUUBOX1     30  //手形、小切手回收ＢＯＸ1 99/0922 三和
#define IMP_TEGATAKOGITTEKAISHUUBOX2     31  //手形、小切手回收ＢＯＸ2 99/0922 三和
#define IMP_WASUREKAISHUUBOX             32  //忘れ回收ＢＯＸ 99/0922 三和
#define IMP_MICRRIBBON                   33  //ＭＩＣＲリボン浓淡 99/10/12 三和

#define PBM_EXHOPPER1          34            //扩张ホッパ１状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_EXHOPPER2          35            //扩张ホッパ２状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_EXHOPPER3          36            //扩张ホッパ３状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_EXHOPPER4          37            //扩张ホッパ４状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_EXHOPPER5          38            //扩张ホッパ５状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_EXHOPPER6          39            //扩张ホッパ６状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_EXHOPPER7          40            //扩张ホッパ７状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_EXHOPPER8          41            //扩张ホッパ８状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_EXHOPPER9          42            //扩张ホッパ９状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_EXHOPPER10         43            //扩张ホッパ１０状态   99/11/26 TMBP 东京三菱ＡＰＩＭ
#define PBM_RJBOX              44            //ＰＢＭＲＪＢＯＸ状态 99/11/26 TMBP 东京三菱ＡＰＩＭ
*/


#define TORIHIKI_NG     0
#define TORIHIKI_OK     1
#define TORIHIKI_HEIKYOKU   2
#define TORIHIKI_HEI_MODE   3
#define TORIHIKI_LINEERR    4
#define TORIHIKI_NE     5
#define TORIHIKI_CANCEL     6

#define MODE_SET    0
#define HABA_HIRO   1
#define HABA_SEMA   2
#define PITCH_15    1
#define PITCH_2     2
#define PITCH_15F   3

// デ－タ取得

#define ST_UNIT         0
#define ST_PAPER       1
#define ST_MEDIA       2
#define ST_DOUSA        3
#define ST_WTERR        4
#define ST_CARD         5
#define ST_YUKOU        6
#define ST_KAISYU       7
#define ST_EMBOSS       8
#define ST_COLLECTIONBOX        9
#define ST_RENWTERR     10
#define ST_INJI         11
#define ST_MAEINJI      12
#define ST_SUSPEND     13
#define ST_ATOINJI      14
#define ST_MAEHOPA      15
#define ST_USHIROHOPA       16
#define ST_OLDTCM       17
#define ST_NEWTCM       18
//#define ST_WTERR_REN        19
#define ST_HAKKOU_UNIT      20
#define ST_KAISYUMAI        21
#define ST_HALT       22
#define ST_HAKKOUKYUSHI     23
#define ST_N_O_CARD     24
#define ST_SHITEN       25
#define ST_GINKOU       26
#define ST_FILE         27
#define ST_RIBON        28
#define ST_TCMHOPA      29
#define ST_KIKIKOUSEI       30
#define ST_AUTOSYUKUTAI     31
#define ST_CUT          32
#define ST_JYOUKYO      33
//#define ST_CARDJUNJYO       34
#define ST_HYOURIERR        35
#define ST_NEWWTERR     36
#define ST_OLDWTERR     37
#define ST_MSWRITEUMU       38
#define ST_DATOUCHK     39
#define ST_SHUTTER      40
#define ST_SOUNYUGUTI       41
#define ST_UNITSET      42
//#define ST_READEND      43
#define  ST_COLLECTIONMEDIA    44
//#define ST_DATASET      45
#define ST_PBINJI       48
//#define ST_WRITEEXISTENCE     49
#define ST_JAMEXISTENCE      50
//#define ST_CARD_RW      51
//#define ST_CARD_RP1     52
//#define ST_CARD_RP2     53
#define ST_TOUROKU      54
#define ST_PBMUNIT      55

#define ST_INJI_DT      56
#define ST_SHIJIMOTO        57
#define ST_INJIPOSRD        58
#define ST_SPR          59
#define ST_HABA         60
#define ST_PITCH        61
#define ST_BRMBOX       62
#define ST_COMBOX       63
#define ST_RERRINF      64
#define ST_HAKKOUERR        65
#define ST_READKYUSHI       66
#define ST_MAEYOUSHI        67
#define ST_USHIROYOUSHI     68
//#define ST_DVEP_TYPE        69
#define ST_KAKUTEIPB_CHK    70
#define ST_BAITAIICHI       71
#define ST_RIBONSET         72
#define ST_KYOUSEITORI        77    // 强制拔取り状态
#define ST_SPLLOCKDATA      78      // SPL自动机担当者登录テ＂—タ
#define ST_LOCKOFFBUFF      79      // 电磁ロック解除部位ハ＂ッファ
#define ST_LOCKOFFSU        80      // 电磁ロック解除部位数
#define ST_NEWPB         82         // 缲り出し通帐有无
#define ST_OLDPB         83         // 插入通帐有无
#define ST_WTERRCNT_H         84    // 缲り出し通帐MSライトエラ－回数
#define ST_RENWTERR_H         85    // 缲り出し通帐MS连续ライトエラ－有无
#define ST_WTERRCNT         86      // 插入通帐ライトエラ－回数
#define ST_HANSOURO         87      // 搬送路上の媒体有无
#define ST_TAIHIRO         88       // 退避路上の媒体有无
#define ST_JNL_MAISUU_T     90    // 电子ジャ－ナル印字枚数情报 单票专用96.12.04
#define ST_EMBOSS_MAISUU_T  91    // エンボス印字枚数情报 单票专用96.12.04
#define ST_TPYOUSHI         97    //　单票用纸状态(假96.12.04 水谷)
#define ST_WTERR_H          101   //　ライトエラ－回数(假96.12.04 水谷)
#define ST_EXHOPPERA1YOUSHI     104     // 扩张ホッパＡ１状态       98.08.21 NSB
#define ST_EXHOPPERA2YOUSHI     105     // 扩张ホッパＡ２状态       98.08.21 NSB
#define ST_EXHOPPERA3YOUSHI     106     // 扩张ホッパＡ３状态       98.08.21 NSB
#define ST_EXHOPPERA4YOUSHI     107     // 扩张ホッパＡ４状态       98.08.21 NSB
#define ST_EXHOPPERA1UMU        108     // 扩张ホッパＡ１有无       98.08.21 NSB
#define ST_EXHOPPERA2UMU        109     // 扩张ホッパＡ２有无       98.08.21 NSB
#define ST_EXHOPPERA3UMU        110     // 扩张ホッパＡ３有无       98.08.21 NSB
#define ST_EXHOPPERA4UMU        111     // 扩张ホッパＡ４有无       98.08.21 NSB
#define ST_NACS_YOUSHI          112     // ＪＮＬ用纸状态（NACS通知用) 98.10.28 TMB
#define ST_SATSUSUU_CASSETTE1   113     // カセット１通帐册数       99/05/08 SBK
#define ST_SATSUSUU_CASSETTE2   114     // カセット２通帐册数       99/05/08 SBK
#define ST_AUTOLOADUMU          115     // 用纸自动补充有无         99/05/31 STD

#define ST_BAUNIT                    116  //(媒体ユニット有无)    NEW 99/09/22 三和
#define ST_DBKINOU                   117  //(テ＂ハ＂イスの机能)    NEW 99/09/22 三和
#define ST_DBTYPE                    118  //(物理テ＂ハ＂イスのタイフ°)    NEW 99/09/22 三和
#define ST_ENTRANCE                  119  //(出入口の媒体有无)    NEW 99/09/22 三和
#define ST_MEPOSITION                124  //(媒体残留种类)    NEW 99/09/22 三和
#define ST_SEIGYOSHURUI              126  //(テ＂ハ＂イスが行える媒体の制御方式)    NEW 99/09/28 三和
#define ST_UNITICHI                  134  //(ユニットのセット状态)    NEW 99/09/22 三和
#define ST_WRERRCNT                  135  //(媒体ライトエラ—回数)    NEW 99/09/22 三和
#define ST_UNITRESET                 136  //(ユニットリセット) NEW 99/09/22 三和
#define ST_TORIWASUREKAISHU          137  //(忘れ回收  回收箱) NEW 99/09/28 三和
#define ST_WASUREKAISHUKAFUKA        138  //忘れ回收动作可／不可 99/09/24 三和
#define ST_SOUNYUHORYU               139  //插入口保留位置 99/09/28 三和
#define ST_HENKYAKUHORYU             140  //返却口保留位置 99/09/28 三和
#define ST_RIBONNOUDO                141  //印字リボン浓度 99/09/28 三和
#define ST_MICRNOUTANZANRYOUJYOOUHOU 142  //MICRリボン浓淡残量情报 99/09/28 三和
#define ST_SUITOUINKNOUDO            143  //スタンプインク浓度 99/09/28 三和

#define ST_RJ                        144  // リジェクト回收状态           99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_RJKAISYUBOX               145  // ＲＪ回收箱状态               99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_RJKAISYUBAITAI            146  // ＲＪ箱媒体有无               99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_RJKAISYUMAI               147  // ＲＪ箱回收枚数               99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_PBSKYUSHI                 148  // ＰＢＳ休止状态               99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_PBSUNIT                   149  // ＰＢＳユニット有无           99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_EXTRAUNIT                 150  // 扩张（ＰＢＳ）ユニット状态   99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_EXTRAUNIT2                151  // 扩张（ＰＢＳ）ユニット状态２ 99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_OLDPBKAISHU               168  // 吸入通帐回收状态             99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_NEWPBKAISHU               169  // 发行通帐回收状态             99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_PBSBAITAI                 172  // ＰＢＳユニット通帐有／无し   99/11/26 TMBP 东京三菱ＡＰＩＭ
#define ST_INJI_UMU                  173  // ＪＮＬモ－ドボタン状态       99/12/14 LAK
#define ST_KENSAKU_INJI              174  // ＪＮＬ范围检索印字指定       99/12/14 LAK
#define ST_FUMEIKAISHU               175  // 不明媒体回收状态             99/12/24 TMBP 东京三菱ＡＰＩＭ

#define ST_ZANRYUUSAKIHAISHUTSU      176  // 残留媒体（领收书/控え）の先に排出するもの 99/12/27 SBK
#define ST_SHOUGAILOG_GENSEDAI       177  // 障害ログ现世代               99/12/29 TMBP 东京三菱ＡＰＩＭ
#define ST_SHOUGAILOG_ZENSEDAI       178  // 障害ログ前世代               99/12/29 TMBP 东京三菱ＡＰＩＭ
#define ST_FUMEI                     179  // 不明媒体有无                 00/03/13 TMBP 东京三菱ＡＰＩＭ
#define ST_PBSHANSOURO               180  // ＰＢＳ搬送路上の媒体有无     00/03/13 TMBP 东京三菱ＡＰＩＭ

#define ST_TRACK2READ                181  // TRACK2 READ STATUS OK OR NG    CST00001
#define ST_TRACK3READ                182  // TRACK3 READ STATUS OK OR NG    CST00001

#define ST_IC_SECURITYSTATUS    183  //ICCard-CSTV4
#define ST_IC_CARDUNITTYPE      184  //ICCard-CSTV4
#define ST_IC_SECURITYTYPE      185  //ICCard-CSTV4
#define ST_IC_ICRWSUPP        186  //ICCard-CSTV4
#define ST_IC_SIMCARDSTATUS     187  //ICCard-CSTV4
#define ST_IC_ICCARDSTATUS      188  //ICCard-CSTV4


#define ST_CRDHALT                   189  //CARDUNIT休止状态        //CST30014
#define ST_SPRHALT                   190  //明细票UNIT休止状态  //CST30025

#define ST_PBRetractBoxUnit         191  //passbook retract box unit状态    //CST30035
#define ST_ICTRACK2READ     192 //CST30044
#define ST_ICTRACK3READ     193 //CST30044
#define ST_LENGTHERR        194 //カード長さ異常

#define ST_CARRYWAY1        195                                                 //CST70014
#define ST_CARRYWAY2        196                                                 //CST70014
#define ST_CARRYWAY3        197                                                 //CST70014
#define ST_CARRYWAY4        198                                                 //CST70014
#define ST_MEDIA_TAKEN      200                                                 //CST70014
#define ST_PRINT_HEAD       201                                                 //CST70022
#define ST_PRINT_HEAD_SETNG 202                                                 //CST70022
#define ST_CARRYWAY_SETNG   203                                                 //CST70022
#define ST_ROLLER           204                                                 //CST70022
#define ST_FORGETCARD       205                                                 //CST70423
#define ST_INDICATECOLLECT  206                                                 //CST70423
#define ST_MEDIA_SP         207                                                 //CK#0099
#define ST_IC_ACTIVATED     208                                                 //ICB63004
#define ST_HICOSUPPORT      209                                                 //ICB63004
#define ST_ICACT_EXIST      210                                                 //ICB63004
#define ST_AUTOWRITESUPPORT 211                                                 //GST10014
#define ST_RETRACT_SUPP     212                                                 //GST10018
#define ST_PARK_SUPP        213                                                 //GST10018
#define ST_LOCOSUPPORT      214                                                 //GST10021
#define ST_CLEARCARDCOUNT   215                                                 //GST10370
#define ST_ACTERR           216                                                 //GV101004
#define ST_ACTEXIST         217                                                 //GV101004

#define SPL_LST_OK          0                                                   //CST70014
#define SPL_LST_NG          1                                                   //CST70014
#define SPL_STS_UNYOU_KAISHIBI_INJI             662 // 运用开始日印字           //CST70014
#define SPL_STS_UNYOU_KAISHIBI_SETTEI           660 // 运用开始日设定           //CST70014
#define SPL_STS_LAMPTEST_START                  142 //  ランプテスト开始        //CST70014
#define SPL_STS_LAMPTEST_END                    143 //  ランプテスト终了        //CST70014
#define SPL_STS_SETTEINAIYOUINJI_START          55  //  设定内容印字开始        //CST70014
#define SPL_STS_SETTEINAIYOUINJI_END            56  //  设定内容印字终了        //CST70014
#define SPL_STS_SHOUGAI_START                   11  //  障害发生                //CST70014
#define SPL_STS_SHOUGAI_END                     12  //  障害回复                //CST70014
#define SPL_STS_UPDOWNDEAL_START                392 //  业务终了处理开始        //CST70014
#define SPL_STS_UPDOWNDEAL_END                  393 //  业务终了处理终了        //CST70014
#define SPL_STS_BJIDOUHOJUU_START               35  //  纸币自动补充开始        //CST70014
#define SPL_STS_BJIDOUHOJUU_END                 36  //  纸币自动补充终了        //CST70014
#define SPL_STS_GOUKEI_START                    15  //  合计开始                //CST70014
#define SPL_STS_GOUKEI_END                      16  //  合计终了                //CST70014
#define SPL_STS_SHOUKEI_START                   13  //  小计开始                //CST70014
#define SPL_STS_SHOUKEI_END                     14  //  小计终了                //CST70014
#define SPL_STS_SHIHEISOUTENSETTEI_START        386  //  纸币装填设定开始       //CST70014
#define SPL_STS_SHIHEISOUTENSETTEI_END          387  //  纸币装填设定终了       //CST70014
#define SPL_STS_SHIHEISOUTENSHOUKAI_INJI_START  388  //  纸币装填照会印字开始   //CST70014
#define SPL_STS_SHIHEISOUTENSHOUKAI_INJI_END    389  //  纸币装填照会印字终了   //CST70014
#define SPL_STS_BAITAIHENKYAKU_START            49  //  媒体返却开始            //CST70014
#define SPL_STS_BAITAIHENKYAKU_END              50  //  媒体返却终了            //CST70014
#define SPL_STS_PROGRAMREVINJI_START            67  //プログラムレビジョン印字开始//CST70014
#define SPL_STS_PROGRAMREVINJI_END              68  //プログラムレビジョン印字终了//CST70014
#define SPL_STS_JNLKENSAKU_RESULTINJI_START     53  //  ＪＮＬ检索结果印字开始  //CST70014
#define SPL_STS_JNLKENSAKU_RESULTINJI_END       54  //  ＪＮＬ检索结果印字终了  //CST70014
#define SPL_STS_KAIKYOKU_START                  3   //  开局处理开始            //CST70014
#define SPL_STS_KAIKYOKU_END                    4   //  开局处理终了            //CST70014
#define SPL_STS_HEIKYOKU_START                  7   //  闭局处理开始            //CST70014
#define SPL_STS_HEIKYOKU_END                    8   //  闭局处理终了            //CST70014
#define SPL_STS_HOSTSEND_START                  394 //  中央交信开始            //CST70014
#define SPL_STS_HOSTSEND_END                    395 //  中央交信终了            //CST70014
#define SPL_STS_RESET_START                     5   //  リセット处理开始        //CST70014
#define SPL_STS_RESET_END                       6   //  リセット处理终了        //CST70014
#

// ＯＰＬ指示
#define OPL_KAIKYOKU        542
#define OPL_RESET       543
#define OPL_HEIKYOKU        544
#define OPL_BAITAIHENKYAKU  545
#define OPL_SOUTEN      546
#define OPL_KAISYU      547
#define OPL_YOBI1       548
#define OPL_YOBI2       549
#define OPL_FUTAHEI     550
#define OPL_LAMPTEST        551
#define OPL_KIKITENKEN      552
#define OPL_GOUKEI      553
#define OPL_SHOUKEI     554
#define OPL_UNNYOU      555                                                     //APL 99/06/23
// ＯＰＬキ－タッチダウン通知
#define OPL_KEY_TOUCHDOWN   0xA001


// ＮＡＣＳコマンド处理（ＳＰＬ假想キ－に割りあてる。０ｘＢ０００～）
#define NAC_KEY_CARD_UKETSUKE       0xB001              // カ－ド受付
#define NAC_KEY_CARD_HENKYAKU       0xB002              // カ－ド返却
#define NAC_KEY_CARD_REPLAY         0xB003              // カ－ド返却（再操作画面付）
#define NAC_KEY_CARD_TORIKOMI       0xB004              // カ－ド取入
#define NAC_KEY_CARD_KAISHUU        0xB005              // カ－ド回收
#define NAC_KEY_PBM_UKETSUKE        0xB006              // 通帐受付
#define NAC_KEY_PBM_HENKYAKU        0xB007              // 通帐返却
#define NAC_KEY_PBM_REPLAY          0xB008              // 通帐返却（再操作画面付）
#define NAC_KEY_PBM_TORIKOMI        0xB009              // 通帐取入
#define NAC_KEY_PBM_KAISHUU         0xB010              // 通帐回收
#define NAC_KEY_SPR_HOUSHUTSU       0xB011              // 明细票放出
#define NAC_KEY_SPR_KAISHUU         0xB012              // 明细票回收
#define NAC_KEY_BC_KEISUU           0xB013              // 现金受付·计数
#define NAC_KEY_BC_HENKYAKU         0xB014              // 现金返却
#define NAC_KEY_BC_KAISHUU          0xB015              // 现金回收
#define NAC_KEY_BC_SHUUNOU          0xB016              // 现金收纳
#define NAC_KEY_ALLTOBIRA_OPEN      0xB017              // 全扉オ－プン
#define NAC_KEY_ALLTOBIRA_CLOSE     0xB018              // 全扉クロ－ズ
#define NAC_KEY_BILL_KEISUU         0xB019              // 纸币受付·计数
#define NAC_KEY_BILL_HENKYAKU       0xB020              // 纸币返却
#define NAC_KEY_BILL_KAISHUU        0xB021              // 纸币回收
#define NAC_KEY_BILL_SHUUNOU        0xB022              // 纸币收纳
#define NAC_KEY_BILLTOBIRA_OPEN     0xB023              // 纸币扉オ－プン
#define NAC_KEY_BILLTOBIRA_CLOSE    0xB024              // 纸币扉クロ－ズ
#define NAC_KEY_COIN_KEISUU         0xB025              // 硬货受付·计数
#define NAC_KEY_COIN_HENKYAKU       0xB026              // 硬货返却
#define NAC_KEY_COIN_KAISHUU        0xB027              // 硬货回收
#define NAC_KEY_COIN_SHUUNOU        0xB028              // 硬货收纳
#define NAC_KEY_COINTOBIRA_OPEN     0xB029              // 硬货扉オ－プン
#define NAC_KEY_COINTOBIRA_CLOSE    0xB030              // 硬货扉クロ－ズ
#define NAC_KEY_AZUKARI_HAKKOU      0xB031              // 预り证发行
#define NAC_KEY_BC_HOUSHUTSU        0xB032              // 现金放出
#define NAC_KEY_SHIHARAITORIHIKI    0xB033              // 支　取引移行
#define NAC_KEY_SHORIZOKKOU         0xB034              // 处理续行
#define NAC_KEY_HONNIN_CARDPASS     0xB035              // 本人确认、カ－ド受付·暗证入力
#define NAC_KEY_HONNIN_PASS         0xB036              // 本人确认、暗证入力
#define NAC_KEY_FMEISAI_INJI        0xB039              // 振入明细帐印字
#define NAC_KEY_RJ_KAISHUU          0xB040              // リジェクト库回收
#define NAC_KEY_POWER_ON            0xB041              // ＰＯＷＥＲ　ＯＮ（电源投入）
#define NAC_KEY_POWER_OFF           0X0B42              // ＰＯＷＥＲ　ＯＦＦ（电源断）
#define NAC_KEY_GAMEN_KIRIKAE       0xB043              // 画面切替
#define NAC_KEY_ALL_RESET           0xB044              // 全モジュ－ルリセット
#define NAC_KEY_BC_RESET            0xB045              // 全现金モジュ－ルリセット
#define NAC_KEY_CARD_RESET          0xB046              // カ－ドモジュ－ルリセット
#define NAC_KEY_PBM_RESET           0xB047              // 通帐モジュ－ルリセット
#define NAC_KEY_BILL_RESET          0xB048              // 纸币モジュ－ルリセット
#define NAC_KEY_COIN_RESET          0xB049              // 硬货モジュ－ルリセット
#define NAC_KEY_MODESHIJI           0xB060              // 运用·取汲モ－ド指示
#define NAC_KEY_DAIKOUSHIHARAI      0xB064              // 代行支
#define NAC_KEY_MTC_SHUUKEI         0xB066              // ＭＴＣ集计
#define NAC_KEY_RYOUSHUU_TAKI       0xB06B              // 媒体制御指示代替领收书发行指示（他机）
#define NAC_KEY_RYOUSHUU_JIKI       0xB06C              // 媒体制御指示代替领收书发行指示（自机）
#define NAC_KEY_SHOUKEI_SHUUSHUU    0xB072              // 小计デ－タ收集
#define NAC_KEY_JOUTAI_YOUKYUU      0xB080              // 状态センス要求
#define NAC_KEY_SYSTEM_INFO         0xB081              // 自动机システム情报
#define NAC_KEY_MESSAGE_HAISHIN     0xB082              // メッセ－ジ配信
#define NAC_KEY_GAMEN_SHOUKAI       0xB083              // 画面番号照会
#define NAC_KEY_TALLY_SHOUKAI       0xB084              // 媒体タリ－デ－タ照会
#define NAC_KEY_BILL_SEISA          0xB085              // 自动精查（纸币のみ）
#define NAC_KEY_BC_SEISA            0xB086              // 自动精查（纸币と硬货）
#define NAC_KEY_GOUKEI_SHOUKEI_INJI 0xB087              // ＣＭＯＳクリア／合·小计印字
#define NAC_KEY_REBOOT              0xB088              // リブ－ト指示

// ファイル配信                                                              //MHP:98/08/20
#define NAC_KEY_FMS_START           0xB100              // ファイル配信开始  //MHP:98/08/20
#define NAC_KEY_FMS_END             0xB101              // ファイル配信终了  //MHP:98/08/20

// ＮＥＴＭ用
#define NETM_START        1     // タ＂ウンロ—ト＂开始指示
#define NETM_REBOOT       2     // リフ＂—ト指示
#define NETM_DWNLDEND     3     // タ＂ウンロ—ト＂终了

/*  メッセ－ジオブジェクト */
/*      通信型            */
#define CALLTYPE_FUNC       1
#define CALLTYPE_ANSWER     2
#define CALLTYPE_POST       3



/* ランプＤＬＬ　　  */
#define LAMPNUM                 40                  // ランプ数
#define LAMPON                  0x01                // ランプ制御デ－タ
#define LAMPOFF                 0x02                //
#define LAMP_W                  0x03                // VKD FUNC ID
#define BUZZ_W                  0x08                //
#define BUZZ_Tan                0x0001              // VKD SUBFUNC ID
#define BUZZ_Ren                0x0002              //
#define BUZZ_Off                0x0000              //
#define Dev_ID_KB               0x000D              // VKD Dev_ID
#define API_No_KB               0x0002              // VKD API_No_KB

/* ステ－タスＤＬＬ  */
#define STS_STSNUM      37

// ステ—タスID定义
#define STS_SOUSAKA     0
#define STS_KEIKOKU     1
#define STS_INDSP       2
#define STS_JNLDSP      3
#define STS_SBUFSEND        4
#define STS_SBUFREP     5
#define STS_SBUFBSY     6
#define STS_HEISOKU     7
#define STS_GBUFSEND        8
#define STS_GBUFREP     9
#define STS_GBUFBSY     10
#define STS_DOUSA       11
#define STS_TORIHIKI        12
#define STS_UPPLATEN        13
#define STS_DWPLATEN        14
#define STS_JNLDOUSA        15
#define STS_KEYMODE     16
#define STS_ACCDSP      17
#define STS_HARDCOPY        18
#define STS_NONEPR      19
#define STS_MSDSP       20
#define STS_MCDSP       21
#define STS_UCHIFULL        22
#define STS_CRSON0      23
#define STS_CRSON1      24
#define STS_CRSON2      25
#define STS_TORIMODE        26
#define STS_12SEN       27
#define STS_KEYSYORICYU     28
#define STS_SOUSAKAKANSHIKYOKA  29
#define STS_SOUSAKAHAKKOUCYU    30
#define STS_KURANPUKANSHICYU    31
#define STS_BHTALM      32
#define STS_CHTALM      33
#define STS_RENKEI      34
#define STS_KANAKAN     35
#define STS_TENKEYSHO       36
// 设定值定义
#define STS_TUUYOHEI        1
#define STS_ANYOHEI     2
#define STS_MEIYOHEI1       3
#define STS_MEIYOHEI2       4
#define STS_TUUHEI      5
#define STS_ANHEI       6
#define STS_MEIHEI1     7
#define STS_MEIHEI2     8
#define STS_TENMODE     1
#define STS_TYPEMODE        2
#define STS_ONLINE      1
#define STS_OFFLINE     2
#define STS_RENSYU      3
#define STS_SAINYU      4
#define STS_1SEN        1
#define STS_2SEN        2
#define STS_HORYU1      1
#define STS_HORYU2      2
#define STS_SCREEN      1
#define STS_MSG         2
#define STS_PBPR        3
#define STS_DIRECT      1
#define STS_CHISU       2

//マップデ－タ中コ－ド
#define DONTCARE    3
#define SHIFTJIS    1
#define JIS     0
#define UME_FUKA    1  //??埋め字を付加しない
#define UME_HIDARI  2  //??左诘めの上、后部に埋め字を付加
#define UME_MIGI    3  //??右诘めの上、前部に埋め字を付加

#define MIGIYOSE    OK
#define HIDARIYOSE  OFF

#define SHOWKANA    3
#define SAMEFIELD   2
#define NEXTFIELD   1
#define NODECODE    0

#define KINSI       ON
#define PERMIT       OFF
#define HALT2     ON

#define FUYOU       ON
#define YOU     OFF

#define SEND_YOU    OFF
#define SEND_FUYOU  ON

#define UMEJI_MIGIZUME      UME_MIGI
#define UMEJI_HIDARIZUME    UME_HIDARI
#define UMEJI_FUKASEZU      UME_FUKA

//回线系タスク
#define LINE_SPEED_HIGH         0
#define LINE_SPEED_LOW          1

//受信电文タスク
#define JNL_DATA                        0x0601

//画面タスク

#define BC_TAIPU    2
#define BC_DIRECT   3
#define BC_ECHO     4
#define BC_TENKEY   5
#define BC_CSRATT   6
#define BC_BLIND    7
#define BC_AUTO     8
#define BC_CSUCLR   10
#define BC_CACCLR   11
#define BC_JUNKEY   20
#define BC_PLUS     21
#define BC_MINUS    22
#define BC_ALLTUCHI 23
#define BC_SUPPRESS 24
#define BC_EDIT     25

#define BC_KANA     30
#define BC_EISU     31
#define BC_CANCEL   32

#define BC_LERR     1
#define BC_BSERR    2


#define BC_IOMAP    1
#define BC_DLMAP    2
#define BC_FAMAP    3
#define BC_FAMAP2   4
#define BC_MSMAP    5
#define BC_MCMAP    6
#define BC_IDTMAP   7
#define BC_INTMAP   8
#define BC_GMAPT    9
#define BC_DCD      10
#define BC_TRS1T    11
#define BC_DCD_SCH  12//    // DCD SEARCH用
#define BC_NST      13
#define BC_ITFMAP   14
#define BC_IOMAP2   15  // 98/04/03
#define BC_FAMAP3   16
#define BC_FAMAP4   17


// DSPJHO define

#define WNDCOUNT    50

#define BG_GIDKEY       1
#define BG_SITEIGID     2
#define BG_LOGWT        3
#define BG_SITEIQUE     4
#define BG_RENGMN       5
#define BG_OVRPGMN      6
#define BG_JIGMN        7
#define BG_ZENGMN       8
#define BG_HLPGMN       9
#define BG_PAGEGMN      10
#define BG_CHFKAK       11
#define BG_JIGMNSCL     12
#define BG_ZENGMNSCL    13
#define BG_CIDOU        14
#define BG_INHCHK       15
#define BG_SWNDAGN      16
#define BG_CODEGMN      17
#define BG_ONETRKD      18
#define BG_ONESLCTD     19
#define BG_ONETORSLCT   20
#define BG_CTENSYOUTOU  21
#define BG_MSHYOUJI     22
#define BG_THMSHYOUJI   23
#define BG_MCHYOUJI     24
#define BG_TORIKINKAKU  25

#define BG_SFLD_NULL    0
#define BG_SFLD_GMNNO   1
#define BG_SFLD_OPTNO   2
#define BG_SFLD_MODE4   3
#define BG_SFLD_YAKNO   4
#define BG_SFLD_BALANCE 5
#define BG_SFLD_DATE    6
#define BG_SFLD_TIME    7

#define BG_HYOUJI   1
#define BG_CLEAR    2

#define BG_ICN_OFF          0
#define BG_ICN_ON           1
#define BG_ICN_PAINT        2
#define BG_PAINT_ALL        0
#define BG_PAINT_MAP        1
#define BG_PAINT_FLD        2
#define BG_PAINT_BMP        3
#define BG_PAINT_BTN        4
#define BG_PAINT_BTNCHG     5
#define BG_PAINT_ANMCHG     6
#define BG_PAINT_BRINK      7
#define BG_GKIND_LOCAL      0
#define BG_GKIND_TUJYO      1
#define BG_GKIND_WARIKOMI   2
#define BG_PLTMAX           64

#define BG_KMKMAX       32

#define BG_ICNMAX           32

//システム制御タスク

#define SYS_DID_NE  0
#define SYS_DID_I   1
#define SYS_DID_IF  2
#define SYS_DID_F   3


// Hfilt

#define FILE_OK 0
#define FILE_NG -1



// インスト－ルタスク
#define INS_BUTTON                  1       // ボタン
#define INS_BTNLAMP                 2       // ボタンランプ
#define INS_BTN_101                 503     // ロ－ド起动取消
#define INS_BTN_102                 504     // ロ－ド起动确认
#define INS_BTN_201                 505     // ロ－ド实行取消
#define INS_BTN_202                 506     // ロ－ド实行确认
#define INS_BTN_401                 507     // 媒体要求取消
#define INS_BTN_402                 508     // 媒体要求确认
#define INS_BTN_501                 509     // ロ－ド再实行
#define INS_BTN_502                 510     // ロ－ド终了
#define INS_BTN_601                 511     // ロ－ドＦＤ未セット确认
#define INS_BTN_701                 512     // ロ－ド实行中リ－ドエラ－确认
#define INS_BTN_801                 513     // ロ－ド起动时メモリ不足确认
#define INS_BTN_901                 514     // ロ－ドレビジョンファイル不正确认
#define INS_LMP_101                 501     // ロ－ド先＝マスタ＆スレ－ブ
#define INS_LMP_102                 502     // ロ－ド先＝マスタのみ
#define INS_FNO_201                 201     // ロ－ド实行画面ロ－ドプログラム名
#define INS_FNO_301                 301     // ロ－ド实行中画面ロ－ドプログラム名
#define INS_FNO_302                 302     // 实行中ＦＤ枚数
#define INS_FNO_303                 303     // ロ－ド中画面ファイル名
#define INS_FNO_401                 401     // 媒体要求画面ロ－ドプログラム名
#define INS_FNO_402                 402     // 媒体要求画面ＦＤ枚数
#define INS_FNO_501                 501     // ロ－ド终了画面ロ－ドプログラム名

#define INSTDAT_KOBETSUGAMENREV     1       // 个别画面レビジョン 97/02/05 全ユ－ザ
#define INSTDAT_GAMENLOADFILE       2       // 画面ロ－ドでインスト－ルしたファイル 97/02/05 全ユ－ザ
#define INSTDAT_COMMONGAMENREV      3       // 共通画面レビジョン 全ユ－ザ 97/05/09
#define INSTDAT_DKKOBETSUGMNREV     4       // ＤＫ上の个别画面レビジョン 全ユ－ザ 97/05/09
#define INSTDAT_DKCOMMONGMNREV      5       // ＤＫ上の共通画面レビジョン 全ユ－ザ 97/05/09

// デバイスＩＤ定义
#define RAS_DVID_PBPR               0x0010  // PBPR
#define RAS_DVID_HMSR               0x0410  // HMSR
#define RAS_DVID_SLPR               0x0610  // SLPR
#define RAS_DVID_SYOUGAI            0xF010  // 障害情报
#define RAS_DVID_FD                 0x0820  // ＦＤ
#define RAS_DVID_DK                 0x0920  // ＤＫ
#define RAS_DVID_DK2                0x0A20  // ＤＫ(Ｄドライブ)
#define RAS_DVID_IOALP_PBPR         0x0040  // PBPR回线(IOALP)
#define RAS_DVID_IOALP_SLPR         0x0140  // SLPR回线(IOALP)
#define RAS_DVID_IOALP_BHT          0x0240  // BHT回线(IOALP)
#define RAS_DVID_IOALP_NGINT        0x0340  // IOA不正割入(IOALP)
#define RAS_DVID_ATM_TPL            0x0080  // OPLタッチハ°ネル(ATM)

#define RAS_DVID_ATM_ECT            0x00F0  // ATM统计ロキ＂ンク＂
#define RAS_DVID_EPONET             0x00F1  // EPONET用统计ロキ＂ンク＂  2000/10/24 标准NT
#define RAS_ECT_ADD                 0
#define RAS_ECT_SET                 1

/*****************************************************************************
**          Ａ　　　　　（１０００番台）                                　**
*****************************************************************************/


//////////////////////////////////////////////////////////////////////////////
//          Ｂ　　　　　（２０００番台）
//////////////////////////////////////////////////////////////////////////////
#define BG_OK                   2008
#define BG_NG                   2009
#define BG_KDOER                2010
#define BG_BUFOV                2011


//画面制御タスク                                         // 95.06.26 追加(冈本)
#define BGC_BANK                2700
#define BGC_BRANCH              2701
#define BGC_AREA                2702

#define BGC_BASE                0x00
#define BGC_JAPANESE            0x4A
#define BGC_ENGLISH             0x45

#define BGC_LEYE_MAX            5
#define BGC_LEYE_CHG_MAX        5


//////////////////////////////////////////////////////////////////////////////
//          Ｃ　　　　　（３０００番台）
//////////////////////////////////////////////////////////////////////////////
#define CANCEL                  3000
#define CRD_MCRW                3001
#define CRD_ID                  3002
#define CRD_YAKU                3003
#define CRD_IDSET               3004
#define CRD_YAKUSET             3005
#define CRD_MC                  3006
#define CRD_MCSET               3007
#define CA_NOT                  3008
#define CRD_SHIMEI              3009
#define CRD_ANSYOU              3010
#define CRD_IDDATA              3011

//////////////////////////////////////////////////////////////////////////////
//          Ｄ　　　　　（４０００番台）
//////////////////////////////////////////////////////////////////////////////
#define DFE                     4003
#define DATABUF_NG              4004
//（情报取得返り值）
#define DISP_CENTER_DT          4100


/*********  ＡＴＭ　ＥＰ制御系   **********/
#define DVEP_RET_EPDwn          2
#define DVEP_RET_LPDwn          3
#define DVEP_RET_OPNErr         4
#define DVEP_RET_MEMErr         5
#define DVEP_RET_ISErr          6
#define DVEP_RET_TMOut          7
#define DVEP_RET_ETCErr         8

#define DVEP_LampOff            0x00        //ランプ制御
#define DVEP_LampTenmetsu       0x01
#define DVEP_LampOn             0x02

#define DVEP_InitKyousei        0x00        //イニシャライズ
#define DVEP_InitNoKyousei      0x01
#define DVEP_InitSetCstBillInfo 0x02		//40-02-00-d7(PG#0012)

#define DVEP_Inf_VRT            0x00        //情报取得

#define DVEP_BILLSET            0x01        //情报取得
#define DVEP_CSM                0x02
#define DVEP_RJSTK              0x03
#define DVEP_NSTK               0x04
#define DVEP_SYOGAI             0x05
#define DVEP_IBUTU              0x06
#define DVEP_CSMFULL            0x07
#define DVEP_Sounyuguti         0x08
#define DVEP_UNITSET            0x09
#define DVEP_CSTSET             0x0a
#define DVEP_BOX1SET            0x0b        //DVEP_RJBSET   //ICB50036
#define DVEP_CST                0x0c
#define DVEP_RJBS               0x0d
#define DVEP_RJB                0x0e
#define DVEP_KRJB               0x0f
#define DVEP_BOX5SET            0x9D        //13-00-07-02
#define DVEP_BOX4SET            0x10        //DVEP_MAN      //ICB50036
#define DVEP_BOX3SET            0x11        //DVEP_GOSEN    //ICB50036
#define DVEP_BOX2SET            0x12        //DVEP_SEN      //ICB50036
#define DVEP_SONKEN             0x13
#define DVEP_CSTJ               0x14
#define DVEP_RJBJ               0x15
#define DVEP_MANJ               0x16
#define DVEP_GOSENJ             0x17
#define DVEP_SENJ               0x18
#define DVEP_MANCNT             0x19
#define DVEP_GOSENCNT           0x1a
#define DVEP_SENCNT             0x1b
#define DVEP_INJIPOSRD          0x1c
#define DVEP_KAISYUBOX          0x1d
#define DVEP_KAISYUCNT          0x1e
#define DVEP_COINSET            0x1f
#define DVEP_GOHYAKU            0x20
#define DVEP_HYAKU              0x21
#define DVEP_GOJU               0x22
#define DVEP_JU                 0x23
#define DVEP_GO                 0x24
#define DVEP_ITI                0x25
#define DVEP_GOHYAKUJ           0x26
#define DVEP_HYAKUJ             0x27
#define DVEP_GOJUJ              0x28
#define DVEP_JUJ                0x29
#define DVEP_GOJ                0x2a
#define DVEP_ITIJ               0x2b
#define DVEP_GOHYAKUCNT         0x2c
#define DVEP_HYAKUCNT           0x2d
#define DVEP_GOJUCNT            0x2e
#define DVEP_JUCNT              0x2f
#define DVEP_GOCNT              0x30
#define DVEP_ITICNT             0x31
#define DVEP_CSTCNT             0x32
#define DVEP_RIBON              0x33
#define DVEP_TCMHAKKOU          0x34
#define DVEP_UKETYU             0x35
#define DVEP_STOCK              0x36
#define DVEP_YOUSHI             0x37
#define DVEP_MANFULLCNT         0x38
#define DVEP_GOSENFULLCNT       0x39
#define DVEP_SENFULLCNT         0x3a
#define DVEP_GOHYAKUFULLCNT     0x3b
#define DVEP_HYAKUFULLCNT       0x3c
#define DVEP_GOJUFULLCNT        0x3d
#define DVEP_JUFULLCNT          0x3e
#define DVEP_GOFULLCNT          0x3f
#define DVEP_ITIFULLCNT         0x40
#define DVEP_PBHAKKOU           0x41
#define DVEP_TPHAKKOU           0x42
#define DVEP_RJBSJ              0x43
#define DVEP_KRJBJ              0x44
#define DVEP_SONKENJ            0x45
#define DVEP_OVRBJ              0x46
#define DVEP_TCU                0x47
#define DVEP_SHUTTER            0x48
#define DVEP_OVRBX              0x50
#define DVEP_CSTEMP             0x51
#define DVEP_CARDHAICHI         0x52
#define DVEP_SETSW              0x53
#define DVEP_IMRERR             0x54
#define DVEP_OV500              0x55
#define DVEP_OV100              0x56
#define DVEP_OV50               0x57
#define DVEP_OV10               0x58
#define DVEP_OV5                0x59
#define DVEP_OV1                0x5a
#define DVEP_OV500CNT           0x5b
#define DVEP_OV100CNT           0x5c
#define DVEP_OV50CNT            0x5d
#define DVEP_OV10CNT            0x5e
#define DVEP_OV5CNT             0x5f
#define DVEP_OV1CNT             0x60
#define DVEP_CST_FUTA           0x61
#define DVEP_MAIN_YOUSHI        0x62
#define DVEP_SUB_YOUSHI         0x63
#define DVEP_GYOCNT             0x64
#define DVEP_RJB1CNT            0x65        // RJB1枚数
#define DVEP_RJB2CNT            0x66        // RJB2枚数
#define DVEP_RJBSCNT            0x67        // RJBS枚数·装填枚数
#define DVEP_RJBCNT             0x68        // 回收枚数
#define DVEP_KRJBCNT            0x69        // 忘れ回收枚数
#define DVEP_BRM_TYPE           0x6a        // クリ—ン/标准BRMタイフ°
#define DVEP_CST_UMU            0x6b        // 装填库媒体有无
#define DVEP_CSTJUNBI           0x6c        // 纸币カセット准备
#define DVEP_HEIOK              0x6d        // 纸币 シャッタ付近 障害物なし
#define DVEP_ALLJ               0x6e        // 金种状态一括取得
#define DVEP_EPDWN              0x6f        // ＥＰダウン
#define DVEP_ALLCNT             0x70        // 金种枚数一括取得
#define DVEP_SPR                0x71        // ＳＰＲ机构有无

#define DVEP_MC_UMU             0x72        // 磁气カ－ド有无
#define DVEP_OLDTCM_UMU         0x73        // 旧振入券有无
#define DVEP_NEWTCM_UMU         0x74        // 新振入券有无
#define DVEP_CARD_WT            0x75        // カ－ドライト有无
#define DVEP_TCM_WT             0x76        // 振入券ライト有无
#define DVEP_MAEHOPPER          0x77        // 前ホッパ１状态（95.10.30 安田）
#define DVEP_MAEHOPPER2         0x78        // 前ホッパ２状态（95.10.30 安田）
#define DVEP_USHIROHOPPER       0x79        // 后ホッパ１状态（95.10.30 安田）
#define DVEP_USHIROHOPPER2      0x7a        // 后ホッパ２状态（95.10.30 安田）
#define DVEP_HOPPER             0x7b        // ホッパ构成（95.11.09 原拓）
#define DVEP_MSRERR             0x7c        // ＭＳリ－ドエラ－要因(95.11.15 安田)
#define DVEP_TYPE               0x7d        // タイプ情报(96.01.10 原拓)
#define DVEP_RIBONSETIJO        0x7e        // リボンセット异常有无
#define DVEP_BAITAIHAICHI       0x7f        // 媒体配置(96.11.28 安并)
#define DVEP_MAEHOPPERUMU       0x80        // 前ホッパ机构有无(96.11.28 安并)
#define DVEP_USHIROHOPPERUMU    0x81        // 后ホッパ机构有无(96.11.28 安并)
#define DVEP_BOUKIN             0x82        // 棒金检知硬货有无
#define DVEP_SENSOR             0x83        // 电サ回线用センサ情报（96.10.09新田）
#define DVEP_PBMAEHP            0x84        // 通帐前ホッパ搭载有无(96.11.26 安并)
#define DVEP_PBUSHIROHP         0x85        // 通帐后ホッパ搭载有无(96.11.26 安并)
#define DVEP_TPMAEHP            0x86        // 单票前ホッパ搭载有无(96.11.26 安并)
#define DVEP_TPUSHIROHP         0x87        // 单票后ホッパ搭载有无(96.11.26 安并)
#define DVEP_MAEHAKKOU          0x88        // 前ホッパ状态(96.11.28 安并)
#define DVEP_USHIROHAKKOU       0x89        // 后ホッパ状态(96.11.28 安并)
#define DVEP_CSTEMP_SHITA       0x8a        // 装填库下确定フラグ(97.02.21 原) 97/02/24 ミドル
#define DVEP_CST_SHITA          0x8b        // 装填库下媒体有无(97.02.21 原) 97/02/24 ミドル
#define DVEP_ALLJ_SONKEN        0x8c        // 全金种状态(FRB含む)(97.02.21 原) 97/02/24 ミドル
#define DVEP_ALLCNT_SONKEN      0x8d        // 全金种枚数(FRB含む)(97.02.21 原) 97/02/24 ミドル
#define DVEP_CSTFULLCNT         0x8e        // 装填库满杯枚数(97.02.21 原) 97/02/24 ミドル
#define DVEP_SONKENFULLCNT      0x8f        // 损券库满杯枚数(97.02.21 原) 97/02/24 ミドル
#define DVEP_RJ_SYOSAI          0x90        // ＲＪ详细(97.02.21 原) 97/02/24 ミドル
#define DVEP_RJB_KAKUTEI        0x91        // ＲＪ库有高确定(97.02.21 原) 97/02/24 ミドル
#define DVEP_CARDSOUNYUU        0x92        // カ－ド插入有无 97/03/28 ミドル
#define DVEP_KURIDASHITOUTATSU  0x93        // 纸币缲出到达枚数 97/11/29 ミドル
#define DVEP_HIKANRYUURBJ       0x94        // 非还流ＲＢ状态 97/12/17
#define DVEP_HIKANRYUURBCNT     0x95        // 非还流ＲＢ枚数 97/12/17
#define DVEP_MAETOBIRA          0x96        // 前搬送路(前扉) WBRM 2000/02/02 ATOM-NT
//HQY
#define DVEP_NISENJ             0x97        // 2000Reject
#define DVEP_USHIROTOBIRA       0x98        // BRM后扉  WBRM  2001/04/16 ATOM-NT

#define DVEP_NISENCNT           0x99        // ICB00025
#define DVEP_NISEN              0x9A        // ICB00025
#define DVEP_NISENFULLCNT       0x9B        // ICB00025 2001/07/25

#define DVEP_UESHUTTER          0xA0        // 上侧シャッタ开闭状态(97.06.09 中野)
#define DVEP_TOUNYUPOSJAM       0xA1        // 下侧シャッタ投入口シ＂ャム(97.06.09 中野)
#define DVEP_KCSTSET            0xA2        // 回收カセットセット状态(97.10.02 山田) 97/11/28 小规模
#define DVEP_KCST               0xA3        // 回收カセット媒体有无(97.10.02 山田)  97/11/28 小规模
#define DVEP_KCSTJ              0xA4        // 回收カセット状态(97.10.02 山田)  97/11/28 小规模
#define DVEP_KCSTCNT            0xA5        // 回收カセット媒体枚数(97.10.02 山田)  97/11/28 小规模
#define DVEP_CST_ALLUMU         0xA6        // 装填/补充カセット金种别媒体有无(97/12/02 高岛)  小规模
#define DVEP_MIKEISUU           0xA7        // 未计数媒体有无   98/02/04 ミドル
#define DVEP_EXUNITSET          0xA8        // 扩张ホッパユニットセット状态  98/08/20  ミドル
#define DVEP_EXHOPPERSET        0xA9        // 扩张ホッパホッパセット状态    98/08/20  ミドル
#define DVEP_EXHOPPERA1         0xAA        // 扩张ホッパＡ１状态状态   98.08.21 NSB
#define DVEP_EXHOPPERA2         0xAB        // 扩张ホッパＡ２状态状态   98.08.21 NSB
#define DVEP_EXHOPPERA3         0xAC        // 扩张ホッパＡ３状态状态   98.08.21 NSB
#define DVEP_EXHOPPERA4         0xAD        // 扩张ホッパＡ４状态状态   98.08.21 NSB
#define DVEP_EXHOPPERA1UMU      0xAE        // 扩张ホッパＡ１机能       98.08.21 NSB
#define DVEP_EXHOPPERA2UMU      0xAF        // 扩张ホッパＡ２机能       98.08.21 NSB
#define DVEP_EXHOPPERA3UMU      0xB0        // 扩张ホッパＡ３机能       98.08.21 NSB
#define DVEP_EXHOPPERA4UMU      0xB1        // 扩张ホッパＡ４机能       98.08.21 NSB
#define DVEP_UESHUTTERUMU       0xB2        // 上侧シャッタ有无 98.10.19 ミト＂ル
#define DVEP_CST1SET            0xB3        // 纸币カセット1セット状态     99/04/08 TBK（ＭＣＤ）
#define DVEP_CST2SET            0xB4        // 纸币カセット2セット状态     99/04/08 TBK（ＭＣＤ）
#define DVEP_CST3SET            0xB5        // 纸币カセット3セット状态     99/04/08 TBK（ＭＣＤ）
#define DVEP_KRJBJSET           0xB6        // 纸币忘れ回收BOXセット状态 99/04/08 TBK（ＭＣＤ）
#define DVEP_SPR_AUTOLOAD       0xB7        // 明细票オ－トロ－ド状态   99/05/25 ミト＂ル
#define DVEP_CST1VALUES         0xB8        // 纸币カセット1金种情报            // 99/05/31 TBK
#define DVEP_CST2VALUES         0xB9        // 纸币カセット2金种情报            // 99/05/31 TBK
#define DVEP_CST3VALUES         0xBA        // 纸币カセット3金种情报            // 99/05/31 TBK
#define DVEP_DISPENSEINFO       0xBC        // 纸币出金结果情报         // 99/07/28 TBK
#define DVEP_OVERKOSET          0xBD        // 予备カセット セット状态         // 99/09/03 FBK (GCOM1)
#define DVEP_TSUTSUSET          0xBE        // 筒 セット状态                   // 99/09/03 FBK (GCOM1)
#define DVEP_MEDIA              0xBF        // fwMedia 99/0922 三和
#define DVEP_OUTPUTMEDIATYPE    0xC0        // fwOutputMediatype 99/0922 三和
#define DVEP_READFORM           0xC1        // fwReadForm 99/0922 三和
#define DVEP_EXTENTS            0xC2        // fwExtents 99/0922 三和
#define DVEP_CONTROL            0xC3        // fwControl               テ＂ハ＂イスが行える媒体の制御方式 99/0922 三和
#define DVEP_MAXRETRACT         0xC4        // fwMaxRetract 99/0922 三和
#define DVEP_RECEIPTENTRANCE    0xC5        // fwReceiptStubEntrance  领收书出口の媒体有无 99/0922 三和 99/0922 三和
#define DVEP_UTILITYCHARGESRETRACTBIN   0xC6  //                   fwUtilityChargesRetractBin  公金回收  回收箱 99/0922 三和
#define DVEP_CHECKRETRACTBIN1           0xC7  //                   fwCheckRetractBin1          手形·小切手回收  回收箱１ 99/0922 三和
#define DVEP_CHECKRETRACTBIN2           0xC8  //                   fwCheckRetractBin2          手形·小切手回收  回收箱２ 99/0922 三和
#define DVEP_UTILITYCHARGESMAXRETRACT   0xC9  //デバイス机能(HTC)  fwUtilityChargesMaxRetract  公金リシ＂ェクトホ＂ックス收纳可能枚数 99/0922 三和
#define DVEP_CHECKMAXRETRACT1           0xCA  //                   fwCheckMaxRetract1          手形/小切手リシ＂ェクトホ＂ックス1 收纳可能枚数 99/0922 三和
#define DVEP_CHECKMAXRETRACT2           0xCB  //                   fwCheckMaxRetract2          手形/小切手リシ＂ェクトホ＂ックス2 收纳可能枚数 99/0922 三和
#define DVEP_DEVICE                     0xCC  //デバイス状态 fwDevice 99/09/24 三和

#define DVEP_BCSHUTTER          0xCD        //ICB50036
#define DVEP_CSMUNIT            0xCE        //ICB50036
#define DVEP_CSM_SEP_BILL       0xCF        //ICB50036
#define DVEP_SHUTTER_FORCEOPEN  0xD0        //ICB50036
#define DVEP_BILL_FORCE         0xD1        //ICB50036
#define DVEP_BILL_FORGET        0xD2        //ICB50036
#define DVEP_POWER_ALM          0xD3        //ICB50036
#define DVEP_BC_STOP            0xD4        //ICB50036
#define DVEP_CSMCHECK           0xD5        //GST10017
#define DVEP_SAFEDOOR           0xD6        //GST10017

#define DVEP_CST4SET            0xD7        // 纸币カセット4セット状态    //GST10005
#define DVEP_CST5SET            0xD8        // 纸币カセット5セット状态    //GST10005
#define DVEP_CST6SET            0xD9        // 纸币カセット6セット状态    //GST10005
#define DVEP_CST7SET            0xDA        // 纸币カセット7セット状态    //GST10005
#define DVEP_CST8SET            0xDB        // 纸币カセット8セット状态    //GST10005
#define DVEP_CST9SET            0xDC        // 纸币カセット9セット状态    //GST10005
#define DVEP_CST10SET           0xFC        // 纸币カセット10セット状态   //GST10005

/*CEN/XFS delete by liwei
#define DVEP_EXHOPPERB1         0xCD    // 扩张ホッパＢ１状态状态 99/11/18 ATOM-NT
#define DVEP_EXHOPPERB2         0xCE    // 扩张ホッパＢ２状态状态 99/11/18 ATOM-NT
#define DVEP_EXHOPPERB3         0xCF    // 扩张ホッパＢ３状态状态 99/11/18 ATOM-NT
#define DVEP_EXHOPPERB4         0xD0    // 扩张ホッパＢ４状态状态 99/11/18 ATOM-NT
#define DVEP_EXHOPPERC1         0xD1    // 扩张ホッパＣ１状态状态 99/11/18 ATOM-NT
#define DVEP_EXHOPPERC2         0xD2    // 扩张ホッパＣ２状态状态 99/11/18 ATOM-NT
#define DVEP_EXHOPPERC3         0xD3    // 扩张ホッパＣ３状态状态 99/11/18 ATOM-NT
#define DVEP_EXHOPPERC4         0xD4    // 扩张ホッパＣ４状态状态 99/11/18 ATOM-NT

#define DVEP_EXHOPPERB1UMU      0xD5    // 扩张ホッパＢ１机能     99/11/18 ATOM-NT
#define DVEP_EXHOPPERB2UMU      0xD6    // 扩张ホッパＢ２机能     99/11/18 ATOM-NT
#define DVEP_EXHOPPERB3UMU      0xD7    // 扩张ホッパＢ３机能     99/11/18 ATOM-NT
#define DVEP_EXHOPPERB4UMU      0xD8    // 扩张ホッパＢ４机能     99/11/18 ATOM-NT
#define DVEP_EXHOPPERC1UMU      0xD9    // 扩张ホッパＣ１机能     99/11/18 ATOM-NT
#define DVEP_EXHOPPERC2UMU      0xDA    // 扩张ホッパＣ２机能     99/11/18 ATOM-NT
#define DVEP_EXHOPPERC3UMU      0xDB    // 扩张ホッパＣ３机能     99/11/18 ATOM-NT
#define DVEP_EXHOPPERC4UMU      0xDC    // 扩张ホッパＣ４机能     99/11/18 ATOM-NT
*/

#define DVEP_RJKAISYUBOX        0xDD    // リジェクトボックス状态     99/11/26 TMBP 东京三菱ＡＰＩＭ
#define DVEP_RJKAISYUCNT        0xDE    // リジェクトボックス回收枚数 99/11/26 TMBP 东京三菱ＡＰＩＭ

#define DVEP_FRONTCONVEYER      0xDF    // 纸币前扉セット状态 2000/03/29 45LAK

#define DVEP_BRMTYPE            0xE0    //CSTV3009
#define DVEP_ERRORDETAIL        0xE1    //ICB50045
#define DVEP_RJBILL             0xE2    //ICB50045
#define DVEP_SPECIALBILL        0xE3    //ICB50045
#define DVEP_HARDDETAIL         0xE6    //ICB50045

#define DVEP_2000NYUKIN         0xF0    // 入金サポ－ト有无 2000/05/08 ATOM-NT

#define DVEP_REARCONVEYER       0xF1    // 纸币后扉セット状态 2001/04/16 ATOM-NT

#define DVEP_CST1               0xF2    // 纸币カセット1の残量状态  ICB00025 2001/07/25
#define DVEP_CST2               0xF3    // 纸币カセット2の残量状态  ICB00025 2001/07/25
#define DVEP_CST3               0xF5    // 纸币カセット3の残量状态  CST30019 2002/03/14

#define DVEP_CST4               0xE4    // 纸币カセット4の残量状态  //GST10005
#define DVEP_CST5               0xE5    // 纸币カセット5の残量状态  //GST10005
#define DVEP_CST6               0x9C    // 纸币カセット6の残量状态  //GST10005
#define DVEP_CST7               0xE7    // 纸币カセット7の残量状态  //GST10005
#define DVEP_CST8               0xE8    // 纸币カセット8の残量状态  //GST10005
#define DVEP_CST9               0xE9    // 纸币カセット9の残量状态  //GST10005
#define DVEP_CST10              0xEA    // 纸币カセット10の残量状态 //GST10005

#define DVEP_LOWERUNITSET       0XF4    //下UNIT 设定 UL291 2001/09/11

#define DVEP_URJBDOOR           0x49    //URJB门状态                        //GV101001
#define DVEP_URJBNUMBER         0x4B    //URJB残枚数                        //GV101001
#define DVEP_URJB               0x4C    //URJB媒体状态                      //GV101001

#define DVEP_ESCSHUTTER         0x4D    //ESC Shutter                       //STD40-01-08-01(FS#0002)
#define DVEP_TRAY_ACCESS        0x4A    //TRAY ACCESS                       //STD40-01-08-02(FS#0006)

//GST10005 #define DVEP_ABCSTNUMBER 0xF6    //CST70022

#define DVEP_CST1NUMBER         0XF7    //ICB50045
#define DVEP_CST2NUMBER         0XF8    //ICB50045
#define DVEP_CST3NUMBER         0XF9    //ICB50045

#define DVEP_CST4NUMBER         0xFD    //GST10005
#define DVEP_CST5NUMBER         0xFE    //GST10005
#define DVEP_CST6NUMBER         0xFF    //GST10005
#define DVEP_CST7NUMBER         0xEB    //GST10005
#define DVEP_CST8NUMBER         0xEC    //GST10005
#define DVEP_CST9NUMBER         0xED    //GST10005
#define DVEP_CST10NUMBER        0xEF    //GST10005

#define DVEP_CUINFO             0xFA                    //ICB50045
#define DVEP_MEDIADETAIL        0xFB    //illust lamp   //ICB50010
#define DVEP_NSTKFULL           0x4E    //stacker full  //STD40-00-00-00(UR-SP)
#define DVEP_CIMNSTK            0x4f    //stacker info  //GST10017(PG#00049)

#define DVEP_InjiHoryu          0x00    //印字(SPR,JPR)
#define DVEP_InjiKyoka          0x01

#define DVEP_Tsujyo             0x00    //排出(SPR)
#define DVEP_Ikkatsu            0x01

#define DVEP_CLR_Ari            0x00    //フォ－マット设定(SPR)
#define DVEP_CLR_Nashi          0x01

#define DVEP_MCW_JIS2           0x80    //カ－ドＭＳライト位置(MCU)
#define DVEP_MCW_JIS11          0x40    // ＯＲして使用
#define DVEP_MCW_JIS13          0x10

#define DVEP_PageForward        0       //页替え时の方向指定(PBM)   cst30005
#define DVEP_PageReverse        1       //cst30005
#define DVEP_PageJunRetry       2       //顺方向再页替        99/11/26 TMBP 东京三菱ＡＰＩＭ
#define DVEP_PageGyakuRetry     3       //逆方向再页替        99/11/26 TMBP 东京三菱ＡＰＩＭ

#define DVEP_PageRetry          0x80    //页替えリトライ指定 99/11/18 ATOM-NT

#define DVEP_LockIchi_PBMUnit   0x08    //电磁ロック位置指定
#define DVEP_LockIchi_BRMUnit   0x08    //ＯＲして使用
#define DVEP_LockIchi_BRMRJB    0x02
#define DVEP_LockIchi_BRMCST    0x01
#define DVEP_LockIchi_COMCST    0x08
#define DVEP_LockIchi_COMUnit   0x80
#define DVEP_LockIchi_COMRJB    0x20
#define DVEP_LockIchi_IMPUnit   0x04    //イメ－ジユニット 99/09/24 三和

#define DVEP_LockOn_PBMUnit     0x08    //电磁ロック位置指定
#define DVEP_LockOn_BRMUnit     0x08    // ＯＲして使用
#define DVEP_LockOn_BRMRJB      0x02
#define DVEP_LockOn_BRMCST      0x01
#define DVEP_LockOn_COMCST      0x08
#define DVEP_LockOn_COMUnit     0x80
#define DVEP_LockOn_COMRJB      0x20
#define DVEP_LockOn_IMPUnit     0x04    //イメ－ジユニット 99/09/24 三和

#define DVEP_CutNo              0       //传票カット指定(SPR)
#define DVEP_Cut                1

#define DVEP_RJB1               0       //ＲＪ券スタック指定(BRM)
#define DVEP_RJB2               1

#define DVEP_SaikanNo           0       //再　别指定(BRM)
#define DVEP_Saikan             1

#define DVEP_CSMChkNo           0       //ＣＳＭ残留チェック(BRM)
#define DVEP_CSMChk             1

#define DVEP_Shinken            0x00    // 真券／模拟券モ－ド(BRM)
#define DVEP_Mogiken            0x01
#define DVEP_Hantei             0x02

#define DVEP_ChkAri             0x00    //回收(BRM)
#define DVEP_ChkNashi           0x01

#define DVEP_TeishiAri          0x40    //入金动作指定(BRM)
#define DVEP_TeishiNashi        0x00

#define DVEP_HEIIJO             0x00    //シャッタ闭异常/准正常(BRM)
#define DVEP_HEIJUNSEIJO        0x01

#define DVEP_KIDOARI            0x01    // MOTOR (BRM)
#define DVEP_KIDONASHI          0x00    //

#define DVEP_KAIIJO             0x00
#define DVEP_KAIJUNSEIJO        0x01


#define DVEP_Syuryo_OK          0x10     //终了情报の终了コ－ド
#define DVEP_Syuryo_JunOK       0x18
#define DVEP_Syuryo_Err         0x08
#define DVEP_Box2MissFeed       0x11        //CST2013
#define DVEP_Box3MissFeed       0x12        //CST2013
#define DVEP_Box4MissFeed       0x13        //CST2013
#define DVEP_Box5MissFeed       0x14                                        //GST10005//GST10380
#define DVEP_Syuryo_NE          0x00
#define DVEP_Syuryo_EPDwn       0x01
#define DVEP_Syuryo_LPDwn       0x02
#define DVEP_Syuryo_MEMErr      0x03
#define DVEP_Syuryo_OPNErr      0x04
#define DVEP_Syuryo_ETCErr      0x05
#define DVEP_Syuryo_ISErr       0x06
#define DVEP_Syuryo_TMOut       0x07
#define DVEP_Syuryo_SyokiErr    0x09
#define DVEP_Syuryo_FatalErr    0x0a
#define DVEP_Syuryo_SaiInjiYou  0x0b
#define DVEP_Syuryo_SPErr       0x0c    //WOSA现金オフ＂シ＂ェクト使用(97.06.11)

#define DVEP_ERR_END                0   //障害コ－ド检索
#define DVEP_ERR_DATOU              1
#define DVEP_ERR_EPDWN              2
#define DVEP_ERR_LPDWN              3
#define DVEP_ERR_OPN                4
#define DVEP_ERR_MEM                5
#define DVEP_ERR_EMBOSS             6
#define DVEP_ERR_FUK                7
#define DVEP_ERR_TBL                8
#define DVEP_ERR_FILE               9
#define DVEP_ERR_CMDTOUT            10
#define DVEP_ERR_AUTOLD             11
#define DVEP_ERR_EMBOPN             12
#define DVEP_ERR_ISOPN              13
#define DVEP_ERR_IS                 14
#define DVEP_ERR_MEM2               15
#define DVEP_ERR_LOADERR            16
#define DVEP_ERR_RCV                17
#define DVEP_ERR_EMPTY              18
#define DVEP_ERR_SAIINJIYOU         19
#define DVEP_ERR_FONTDATA           20
#define DVEP_ERR_FONTBUFF           21
#define DVEP_ERR_FONTNOOPEN         22
#define DVEP_ERR_FONTFILE           23
#define DVEP_ERR_NOSYOKI            24
#define DVEP_ERR_KAISYURETRYOVR     25      //11.30 安田
#define DVEP_ERR_NOHOPPER           26      //12.18 安田
#define DVEP_ERR_MITEIGI            27      //96.02.14 原拓
#define DVEP_ERR_PNCMEM             28      //ト＂ライハ＂メモリ确保失败 97.04.16
#define DVEP_ERR_VGCMEM             29      //
#define DVEP_ERR_DCPMEM             30      //
#define DVEP_ERR_LCPMEM             31      //
#define DVEP_ERR_DICEPMEM           32      //
#define DVEP_ERR_IDCMEM             33      //
#define DVEP_ERR_ISMEM              34      //
#define DVEP_ERR_LCDMEM             35      //
#define DVEP_ERR_CCMSMEM            36      //
#define DVEP_ERR_RASMEM             37      //
#define DVEP_ERR_FUKMEM             38      //
#define DVEP_ERR_FLCOPN             39      //97.06.21 友安(フリッカOPEN失败)
#define DVEP_ERR_TPNOHOPPER         40      //单票缲出异常 97.11.21  NTユ—サ＂より依赖
#define DVEP_ERR_DETECT             41      //检知MSリ—ト＂终了 97/12/09  SBK
#define DVEP_ERR_SYUKKINCHECK       42      //出金枚数チェック 98/07/15  SBK
#define DVEP_ERR_FORMDATA           43      //フォ—マット设定テ＂—タ异常 99/11/04 ミト＂ル
#define DVEP_ERR_MEDIADATA          44      //For(SP)
#define DVEP_ERR_PDL_RTYOVR         49      //30-00-00-20
#define DVEP_ERR_PDLDATA_NOFILE     50      //30-00-00-20
#define DVEP_ERR_FILEKANRI_NOFILE   51      //30-00-00-20
#define DVEP_ERR_PDL_ERROR          52      //STD40-00-00-00 UR
#define DVEP_ERR_CNL                98
#define DVEP_ERR_OK                 99
#define DVEP_EPIJYOU                100
#define DVEP_API_ERROR              101     //API_ERROR
#define DVEP_ERR_USB_ADDR           102     //CST70004
#define DVEP_ERR_USB_LOAD           103     //CST70004
#define DVEP_ERR_POWOFF             104     //CST70004
#define DVEP_ERR_DOWNLOAD           105     //ICB62308
#define DVEP_ERR_RETRACTBOX         106     //13-00-04-07
#define DVEP_ERR_PDLKANRI_NOFILE    107     //30-00-00-20
#define DVEP_ERR_JUNOK              108     //30-00-00-20
#define DVEP_ERR_COMMANDERR         109     //30-00-00-20
#define DVEP_ERR_EPDWN2             110     //STD40-00-00-00
#define DVEP_ERR_STOREMONEYCHK      111     //STD40-00-00-00 UR
#define DVEP_ERR_KYOUSEI_TORI       112     //STD40-00-00-00 SPR
#define DVEP_ERR_SETTIMER           113     //STD40-00-00-00 UR
#define DVEP_ERR_CST_NOT_CONFIG		114		//STD40-00-00-00 UR
#define DVEP_ERR_USB_LOAD2				115		//STD40-00-07-02 UR
#define DVEP_ERR_USB_ADDR2				116		//STD40-00-07-02 UR
#define DVEP_ERR_LIB_LOAD				117		//STD40-00-06-01 UR
#define DVEP_ERR_LIB_ADDR				118		//STD40-00-06-01 UR
#define DVEP_ERR_DBTF_SET_TABLE			119		//STD40-00-07-02 UR
#define DVEP_ERR_TRACE_GET_EXEC			120		//STD40-00-07-02 UR
#define DVEP_ERR_SERIAL_IMAGE			121		//STD40-00-07-02 UR
#define DVEP_ERR_WHOLE_IMAGE			122		//STD40-00-07-02 UR
#define DVEP_ERR_ZERO_TRACE				123		//STD40-00-07-02 UR
#define DVEP_ERR_FEATURE_DATA			124		//STD40-00-07-02 UR
#define DVEP_ERR_UNFIT_LEVEL			125		//STD40-00-10-00 UR
#define DVEP_ERR_VERIFICATION_LEVEL		126		//STD40-00-10-00 UR
#define DVEP_ERR_PDLDATA_READERR		127		//STD40-00-00-00 PBM
#define DVEP_ERR_BLACKLIST				128		//STD40-00-13-00 UR
#define DVEP_ERR_ROOMCHECK				129		//STD40-01-08-A3(FS#0014) ADD
#define DVEP_ERR_OPTIONSET				130		//STD40-01-15-14(MRT9#0008) ADD
#define DVEP_ERR_CCRYPTO_LOAD			131		//STD40-01-32-00 ADD UR
#define DVEP_ERR_CCRYPTO_ADDR			132		//STD40-01-32-00 ADD UR
#define DVEP_ERR_CIPHER_INI				133		//STD40-01-32-00 ADD UR
#define DVEP_ERR_CIPHER_FARM			134		//STD40-01-32-00 ADD UR
#define DVEP_ERR_CIPHER_MISMATCH		135		//STD40-01-32-00 ADD UR
#define DVEP_ERR_CIPHER_PDL_INI			136		//STD40-01-32-00 ADD UR
#define DVEP_ERR_LPDWN2					137		//STD40-01-32-10 UR
#define DVEP_ERR_NONEED					138		//STD40-01-32-10(FT#0002) UR
#define DVEP_ERR_NOADMIN				139		//40-02-05-00(PG#00005)
#define DVEP_ERR_ADMINTIMEOUT			140		//40-02-05-00(PG#00005)
#define DVEP_ERR_PWNOTSET				141		//40-02-05-00(PG#00005)
#define DVEP_ERR_NOKEY					142		//40-02-05-00(PG#00005)
#define DVEP_ERR_PWHISTORYERR			143		//40-02-05-00(PG#00005)
#define DVEP_ERR_PWSETOVER				144		//40-02-05-00(PG#00005)
#define DVEP_ERR_PWAUTHERR				145		//40-02-05-00(PG#00005)
#define DVEP_ERR_PWAUTHOVER				146		//40-02-05-00(PG#00005)
#define DVEP_ERR_OPEN_PWNOTSET          147     //40-02-05-00(PG#00005)
#define DVEP_ERR_UNMATCH                148     //40-02-05-00(FT#00005)
#define DVEP_ERR_HIGH_ENERGY_SAVING     149     //40-02-05-B1(MRT2#001)

#define DVEP_ERR_PLATEN             201     // STD40-00-02-02 JPR
#define DVEP_ERR_IOMC               202     // STD40-00-02-02 JPR/SPR

#define DVEP_RW_MC                  0x0100  // カ－ド搬送路管理
#define DVEP_RW_TCM                 0x0200
#define DVEP_RP_MC                  0x0010
#define DVEP_RP_TCM                 0x0020
#define DVEP_RP2_MC                 0x0001
#define DVEP_RP2_TCM                0x0002
#define DVEP_CARD_FUMEI             0x8000
#define DVEP_RW_OLDPB               0x0100  // 媒体配置(PBM)
#define DVEP_RW_NEWPB               0x0200  // 96.11.28(安并)
#define DVEP_RW_TP                  0x0400
#define DVEP_RW_FUMEI               0x0800  // 99/11/18 ATOM-NT
#define DVEP_RW_TP2                 0x2000  // 媒体种别：大型单票(管理簿) 99/11/26 TMBP 东京三菱ＡＰＩＭ
#define DVEP_RP_OLDPB               0x0010
#define DVEP_RP_NEWPB               0x0020
#define DVEP_RP_TP                  0x0040
#define DVEP_RP_FUMEI               0x0080  // 99/11/18 ATOM-NT
#define DVEP_IS_NEWPB               0x1000  // 99/11/18 ATOM-NT
#define DVEP_IS_FUMEI               0x4000  // 00/03/06 ATOM-NT

#define DVEP_IJO                    0
#define DVEP_JUNOK                  1

#define DVEP_CONT                   0       // 通帐印字指定(途中指定)
#define DVEP_END                    1       // 通帐印字指定(最终指定)

#define DVEP_MAEATOSHITEI           0x00    // 缲り出しホッパ  前后(假96.12.04 水谷)
#define DVEP_MAESHITEI              0x01    // 缲り出しホッパ  前(假96.12.04 水谷)
#define DVEP_ATOSHITEI              0x02    // 缲り出しホッパ  后(假96.12.04 水谷)

#define DVEP_UE                     0       // 上指定(97.02.21 原) 97/02/24 ミドル
#define DVEP_SHITA                  1       // 下指定(97.02.21 原) 97/02/24 ミドル

// 纸币缲出到达枚数コマンド情报ＩＤ                 // 97.11.28 SBK
#define DVEP_BRM_NYUUKINKEISUU                  1   // 纸币入金计数
#define DVEP_BRM_NYUUKINSHUUNOU_SAIKANARI       2   // 纸币入金收纳（再　有り）
#define DVEP_BRM_NYUUKINSHUUNOU_SAIKANMODOSHI   3   // 纸币入金收纳（再　返し）
#define DVEP_BRM_NYUUKINSHUUNOU                 4   // 纸币入金收纳（再　无）
#define DVEP_BRM_SHUKKIN                        5   // 纸币出金
#define DVEP_BRM_WASUREKAISHUU                  6   // 纸币忘れ回收
#define DVEP_BRM_TORIKESHIHENKYAKU              7   // 纸币入金取消返却
#define DVEP_BRM_SOUTEN_SAIKANARI               8   // 纸币装填（再　有り）
#define DVEP_BRM_SOUTEN_SAIKANMODOSHI           9   // 纸币装填（再　返し）
#define DVEP_BRM_SOUTEN_SAIKANNASHI             10  // 纸币装填（再　无／补充）
#define DVEP_BRM_KAISHUU                        11  // 纸币回收
#define DVEP_BRM_SEISA_RB3_CST                  12  // 纸币精查（RB3→CST）
#define DVEP_BRM_SEISA_RB1_RB3                  13  // 纸币精查（RB1→RB3）
#define DVEP_BRM_SEISA_RB2_RB1                  14  // 纸币精查（RB2→RB1）
#define DVEP_BRM_SEISA_RB3_RB2                  15  // 纸币精查（RB3→RB2）
#define DVEP_BRM_SEISA_CSM_NSTK                 16  // 纸币精查（CSM→NSTK）
#define DVEP_BRM_SEISA_NSTK_RB12                17  // 纸币精查（NSTK→RB1/2）
#define DVEP_BRM_SEISA_CST_RB3                  18  // 纸币精查（CST→RB3）
#define DVEP_BRM_SEISA_CSM_CST                  19  // 纸币精查（CSM→CST）
#define DVEP_BRM_SEISA_CST_RB3_SAIKAN           20  // 纸币精查（CST→RB3）
#define DVEP_BRM_SHUKKINSHUUNOU_CSM_NSTK        21  // 纸币出金收纳（CSM→NSTK）
#define DVEP_BRM_SHUKKINSHUUNOU_NSTK_RB         22  // 纸币出金收纳（NSTK→RB）
#define DVEP_BRM_SEISA_RB1_CST                  23  // 纸币精查（RB1→CST） :WBRM 2000/02/02 ATOM-NT
#define DVEP_BRM_SEISA_CST_RB1                  24  // 纸币精查（CST→RB1） :WBRM 2000/02/02 ATOM-NT
#define DVEP_BRM_SEISA_RB2_CST                  25  // 纸币精查（RB2→CST） :WBRM 2000/02/02 ATOM-NT
#define DVEP_BRM_SEISA_CST_RB2                  26  // 纸币精查（CST→RB2） :WBRM 2000/02/02 ATOM-NT

#define DVEP_SYUNO1             1       // 硬货收纳     // 2000/04/17 LAK35
#define DVEP_SYUNO2             2       // 硬货收纳２   // 2000/04/17 LAK35
#define DVEP_SYUNO3             3       // 硬货收纳３   // 2000/04/17 LAK35

//****** KAISEN ***********************

#define DVLN_HIGHT              0   // 通信速度 高速
#define DVLN_LOW                1   //          低速
#define DVLN_ALM                9   // 受信通知イヘ＂ント コ—ト＂

// 保守回线タスク 情报取得用 项目ＩＤ
#define DSK_STATUS              4300    // ステ－タス情报
#define DSK_LP                  4301    // ＬＰ状态
#define DSK_LINE                4302    // 回线状态
// 保守回线タスク ステ－タス情报详细
#define DSK_INITWAIT            4301    // 初期设定待ち
#define DSK_INIT                4302    // 初期设定中
#define DSK_OPENWAIT            4303    // 回线オ－プン待ち
#define DSK_OPEN                4304    // 回线オ－プン中
#define DSK_CONNENDWAIT         4305    // 接续要求送信终了待ち(オ－プン)
#define DSK_KIDOWAIT_OPEN       4306    // 受信起动终了待ち(オ－プン)
#define DSK_RETWAIT             4307    // 接续应答待ち
#define DSK_KIDOWAIT            4308    // 受信起动终了待ち(通常)
#define DSK_NEUTRAL             4309    // ニュ－トラル
#define DSK_KIDOWAIT_RCV        4310    // 受信起动终了待ち(通常)
#define DSK_SOSHINWAIT          4311    // 送信终了待ち(通常)
#define DSK_CLOSE               4316    // 回线クロ－ズ中
#define DSK_YOKUSHI             4317    // 抑止
#define DSK_NE                  4318    // イベント读舍て
#define DSK_LINEOFF             4319    // 回线断
#define DSK_WAIT_LINEOFF        4320    // 回线断待ち
#define DSK_RSTWAIT             4321    // ＲＳＴＷａｉｔ
#define DSK_WAIT_TIMEOUT        4322    // タイムアウト待ち
#define DSK_WAIT_KAIJYO         4323    // 准备完オフ回答待ち
#define DSK_CANCEL              4324    // キャンセル



/*****************************************************************************
**          Ｅ　　　　　（５０００番台）                                　**
*****************************************************************************/

// 障害一方通知要因
#define ERR_UNITSET       5200
#define ERR_EPDOWN        5201
#define ERR_EPOFF         5202
#define ERR_ETC           5203
#define DOUSA_TEISHI      5204                                                  //CK#0396
#define TOUCH_ERROR       5205                                                  //CK#0396
//  HSLCP  扩张ファンクション（扩张种别） 96.05.28 犬冢 追加
#define EXT_TERM_SELF    5700       // 扩张识别  TERM_SELF
#define EXT_DLEVEL_RESET 5701       // 扩张识别  Dレヘ＂ルリセット
#define EXT_OPEN_ATENTION 5702      // 扩张识别  开局アテンション  97/06/25
#define EXT_ONLINE_MODE   5703      // 扩张识别  オンラインモ—ト＂   97/06/25
#define EXT_TEST_MODE     5704      // 扩张识别  テストモ—ト＂     97/06/25


//  HSLCP  送信チェ—ン情报
#define SND_USRDT_MIDLCHN            0x0000     // 送信ユ—サ＂テ＂—タ中间チェ—ン
#define SND_USRDT_LASTCHN            0x0010     // 送信ユ—サ＂テ＂—タ最终チェ—ン
#define SND_USRDT_FRSTCHN            0x0020     // 送信ユ—サ＂テ＂—タ先头チェ—ン
#define SND_USRDT_ONLYCHN            0x0030     // 送信ユ—サ＂テ＂—タ单独チェ—ン

//  HSLCP  受信チェ—ン情报
#define RCV_USRDT_MIDLCHN            0x0000     // 受信ユ—サ＂テ＂—タ中间チェ—ン
#define RCV_USRDT_LASTCHN            0x0010     // 受信ユ—サ＂テ＂—タ最终チェ—ン
#define RCV_USRDT_FRSTCHN            0x0020     // 受信ユ—サ＂テ＂—タ先头チェ—ン
#define RCV_USRDT_ONLYCHN            0x0030     // 受信ユ—サ＂テ＂—タ单独チェ—ン
#define RCV_BUTUKARI                 0x0080     // 送受信卫突

// TlsHSLCP  S_Send(wSendID) 送信要求种别
#define LCP_SENDID_NORMAL            0x0000     // 通常
#define LCP_SENDID_UTI_MIDLCHN       0x0100     // ユ—サ＂—テ＂—タ/问合せ/中间テ＂—タ
#define LCP_SENDID_UTI_LASTCHN       0x0110     // ユ—サ＂—テ＂—タ/问合せ/最终テ＂—タ
#define LCP_SENDID_UTI_FRSTCHN       0x0120     // ユ—サ＂—テ＂—タ/问合せ/先头テ＂—タ
#define LCP_SENDID_UTI_ONLYCHN       0x0130     // ユ—サ＂—テ＂—タ/问合せ/单独テ＂—タ
#define LCP_SENDID_UIP_MIDLCHN       0x0180     // ユ—サ＂—テ＂—タ/一方/中间テ＂—タ
#define LCP_SENDID_UIP_LASTCHN       0x0190     // ユ—サ＂—テ＂—タ/一方/最终テ＂—タ
#define LCP_SENDID_UIP_FRSTCHN       0x01a0     // ユ—サ＂—テ＂—タ/一方/先头テ＂—タ
#define LCP_SENDID_UIP_ONLYCHN       0x01b0     // ユ—サ＂—テ＂—タ/一方/单独テ＂—タ
#define LCP_SENDID_INITSELF          0x0203     // INIT-SELF
#define LCP_SENDID_TERMSELF          0x0204     // TERM-SELF
#define LCP_SENDID_RTR               0x0205     // RTR
#define LCP_SENDID_LUSTAT            0x0206     // LUSTAT
#define LCP_SENDID_NOTIFYON          0x0207     // NOTIFY(电源オン)  97/06/25
#define LCP_SENDID_NOTIFYOFF         0x0208     // NOTIFY(电源オフ)  97/06/25
#define LCP_SENDID_MIDLCHN           0x0300     // 中间チェ—ン  97/06/25
#define LCP_SENDID_LASTCHN           0x0301     // 最终チェ—ン  97/06/25
#define LCP_SENDID_FRSTCHN           0x0302     // 先头チェ—ン  97/06/25
#define LCP_SENDID_ONLYCHN           0x0303     // 单独チェ—ン
#define LCP_SENDID_INIT              0x0310     // イニシャル要求アテンション

#define LCP_SENDID_TESTNO            0x0483     // 试验番号  97/06/25

#define LCP_LAN_CCL_FRSTCHN          0x0001     // 先头チェイン
#define LCP_LAN_CCL_MIDLCHN          0x0002     // 中间チェイン
#define LCP_LAN_CCL_LASTCHN          0x0005     // 最终チェイン
#define LCP_LAN_CCL_ONLYCHN          0x0006     // 单独チェイン
#define LCP_LAN_CCL_IUACK            0x0090     // IUACK
#define LCP_LAN_CCL_IUNAK            0x0091     // IUNAK
#define LCP_LAN_CCL_IUCAN            0x00A0     // IUCAN

// TlsHSLCP  S_BufferFree(wBfFreId) バッファフリ－种别
#define LCP_RCVBUFF_OK               0x0000     // 正常终了
#define LCP_RCVBUFF_NG               0x00ff     // 异常终了


// TlsHSOBS  S_Send(wSendID) 送信要求种别 97/02/24 ミドル
#define OBS_SENDID_NORMAL            0x0000     // 通常         97/06/25
#define OBS_SENDID_POW_OFF           0x0001     // Pow-Off要求  97/06/25
#define OBS_SENDID_CONTROL           0x0002     // コントロ—ル要求   97/06/25
#define OBS_SENDID_ONLYCHAIN         0x0003     // 单独チェイン 98/09/10 ミドル
#define OBS_SENDID_INITIAL           0x0004     // イニシャルアテンション  98/09/10 ミドル

// TlsHSOBS  S_BufferFree(wBfFreId) バッファフリ－种别 97/06/25
#define OBS_RCVBUFF_OK               0x0000     // 正常终了 97/06/25
#define OBS_RCVBUFF_NG               0x00ff     // 异常终了 97/06/25

//   HSOBS 扩张ファンクション (关数型)    扩张种别
#define OBS_LFEXT_ATMSTS             0x0001     // ATMステ—タス变更
#define OBS_LFEXT_TORIFLG            0x0002     // 取り汲い中フラグ   99/03/19  ミドル

//  HSLCP 扩张ファンクション（关数型） 扩张种别
#define LFEXT_LCP_ALLBITCLEAR        0x0000     // 全ヒ＂ットクリア 97/06/25
#define LFEXT_LCP_IOALMBITON         0x0001     // I/Oアラ—ムヒ＂ットオン 97/06/25
#define LFEXT_LCP_IOALMBITOFF        0x0002     // I/Oアラ—ムヒ＂ットオフ 97/06/25
#define LFEXT_LCP_LOCALBITON         0x0003     // ロ—カル动作中ヒ＂ットオン 97/06/25
#define LFEXT_LCP_LOCALBITOFF        0x0004     // ロ—カル动作中ヒ＂ットオフ 97/06/25
#define LFEXT_LCP_ENDBITON           0x0005     // 通帐ニアエント＂ヒ＂ットオン 97/06/25
#define LFEXT_LCP_ENDBITOFF          0x0006     // 通帐ニアエント＂ヒ＂ットオフ 97/06/25
#define LFEXT_LCP_LANKOUCYUU_SET     0x1000     // LAN工注セット 98/09/02
#define LFEXT_LCP_KIRIKAEKANOU       0x1001     // ハ＂ックアッフ°切替え可能 98/09/02
#define LFEXT_LCP_MEMDUMP            0xfff0     // LPメモリタ＂ンフ° 97/06/25
// これ以降 LCP LFEXT **** で定义の事
#define LCP_LFEXT_ATMSTS             0x0007     // 扩张识别 ATMステ—タス变更 98/09/29
#define LCP_LFEXT_SEND_T             0x0008     // 扩张识别 送信タイムアウト时间变更 99/05/07 ミト＂ル

//  HSLCP 扩张ファンクション（双方向型） 扩张种别
#define LCP_LFEXT_ER_ON              0x00b1     // 扩张识别 ＥＲオン       2000/02/15 ミト＂ル
#define LCP_LFEXT_ER_OFF             0x00b2     // 扩张识别 ＥＲオフ       2000/02/15 ミト＂ル
#define LCP_LFEXT_ER_OFFON           0x0033     // 扩张识别 ＥＲオフ／オン 2000/02/15 ミト＂ル

//  HSOSI 送信种别
#define OSI_SENDID_BEGIN             0x0001     // TP-BEGIN-DIALOGUE-RI  97/07/31 ミト＂ル
#define OSI_SENDID_TRANSFER          0x0002     // TP-TRANSFER-RI        97/07/31 ミト＂ル
#define OSI_SENDID_ABORT             0x0003     // TP-ABORT-RI           97/07/31 ミト＂ル

//   HSTCP 扩张ファンクション (关数型)    扩张种别
#define LFEXT_TCP_LIFECHKST          0x8001     // 生死管理チェック开始      97/09/08 ミト＂ル

//   HSLTP,HSLUP (TCP/IP TCPソケット/UDPソケット制御)    ソケットＩＤ  97/12/25
#define SOKET_ID_1                   0x0001     // ソケットID 1    97/12/25
#define SOKET_ID_2                   0x0002     // ソケットID 2    97/12/25
#define SOKET_ID_3                   0x0003     // ソケットID 3    97/12/25
#define SOKET_ID_4                   0x0004     // ソケットID 4    97/12/25
#define SOKET_ID_5                   0x0005     // ソケットID 5    97/12/25
#define SOKET_ID_6                   0x0006     // ソケットID 6    97/12/25
#define SOKET_ID_7                   0x0007     // ソケットID 7    97/12/25
#define SOKET_ID_8                   0x0008     // ソケットID 8    97/12/25

//   HSLTP,HSLUP (TCP/IP TCPソケット/UDPソケット制御)    IPアト＂レスタイフ°   98/07/07
#define IPADDR_DEC                   0x0001     // '.'で区切られる１０进数
#define IPADDR_NAME                  0x0002     // HOSTSに定义されているホスト名称
#define IPADDR_HEX                   0x0003     // １６进(４byte)
//                                               ホ°—ト番号タイフ°
#define PORT_NO_DEC                  0x0001     // １０进数
#define PORT_NO_NAME                 0x0002     // Servicesに定义されているホ°—ト名称
#define PORT_NO_HEX                  0x0003     // １６进(1WORD)

//////////////////////////////////////////////////////////////////////////////
//          Ｆ　　　　　（６０００番台）
//////////////////////////////////////////////////////////////////////////////
#define FREE                         6000


//////////////////////////////////////////////////////////////////////////////
//          Ｇ　　　　　（７０００番台）
//////////////////////////////////////////////////////////////////////////////



//////////////////////////////////////////////////////////////////////////////
//          Ｈ　　　　　（８０００番台）
//////////////////////////////////////////////////////////////////////////////


#define HEI_ALM                 8400
#define HEI_JUNBIKAN            8401
#define HEI_KAISEN              8402
#define HEI_PRINTER             8403
#define HEI_LOCAL               8404
#define HEI_END                 8405



//////////////////////////////////////////////////////////////////////////////
//          Ｉ　　　　　（９０００番台）
/////////////////////////////////////////////////////////////////////////////
#define INIT_OK                 9000
#define INIT_NG                 9001
#define IDC                     9100


//////////////////////////////////////////////////////////////////////////////
//          Ｊ　　　　　（１００００番台）
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
//          Ｋ　　　　　（１１０００番台）
//////////////////////////////////////////////////////////////////////////////
#define KAN                     11000

#define KEY_OK                  11010
#define KEY_NG                  11011

#define KEY_POWOFF              11100
#define KEY_KAIKYOKU            11101
#define KEY_HEIKYOKU            11102
#define KEY_RESET               11103
#define KEY_SOUTEN              11104
#define KEY_KAISYU              11105
#define KEY_ICHIBU              11106
#define KEY_SEISA               11107
#define KEY_GOUKEI              11108
#define KEY_SHOUKEI             11109
#define KEY_BAITAIHENKYAKU      11110
#define KEY_BAITAIKAISYU        11111
#define KEY_LAMPTEST            11112
#define KEY_BIF                 11113
#define KEY_PROGRAMVRT          11114
#define KEY_JNLPRINT            11115
#define KEY_SHIHEISOUTEN        11116
#define KEY_SHIHEIKAISYUU       11117
#define KEY_SHIHEISEISA         11118
#define KEY_SHIHEIICHIBU        11119
#define KEY_KOUKASOUTEN         11120
#define KEY_KOUKAKAISYUU        11121
#define KEY_KOUKASEISA          11122
#define KEY_KOUKAICHIBU         11123
#define KEY_BIFVRT              11124
#define KEY_NIFVRT              11125

#define KAISENSYOUGAI           11126

#define KAISEN_BUFFFREE         11901//デバイス制御(ATM)
#define KAISEN_RECOVER          11902
#define KAISEN_ERRDOWN          11903
#define KAISEN_LPDOWN           11904
#define KAISEN_RCV              11905
#define KAISEN_CLOSE            11906
#define KAISEN_INFUPDATE        11907

//////////////////////////////////////////////////////////////////////////////
//          Ｌ　　　　　（１２０００番台）
//////////////////////////////////////////////////////////////////////////////
#define LINE_TROUBLE            12000

#define LINE_SETUDAN            12008
#define LINE_ALM                12009
#define LINE_POSSIBLE              12010
#define LINE_CANNOT              12011
#define LINE_RST                12012
#define LINE_OK                 12013
#define LINE_NODOWN_TIMEOUT     12014
#define LINE_SNDFUKA            12015
#define LINE_TSELF_DAN          12016           //96.02.21 SNA 日比野
#define LINE_IRT_RCV            12017           //IRT 受信通知  97/06/25
#define LINE_BACKUP             12018           //ハ＂ックアッフ°切换通知  97/07/15 ミト＂ル
#define LINE_MODOSHI            12019           //ハ＂ックアッフ°返し通知  97/07/15 ミト＂ル
#define LINE_REBOOT             12020           //REBOOT通知  98/09/02 ミト＂ル
#define LINE_KIRIKAE            12021           //サ—ハ＂切替え通知  98/09/02 ミト＂ル
#define LINE_INIINF_ERR         12022           //ATMLAN.INI异常  99/11/08 AKG

#define LINE_OPIM3_NG           12100           //97.06.25 第３银行
#define LINE_SYOUGAI_FIRST_BLOCK 12101          //97.09.19 ＮＮＳ

#define LCO_CENTERPASS          12999           //97/07/22 劳金
//////////////////////////////////////////////////////////////////////////////
//          Ｍ　　　　　（１３０００番台）
//////////////////////////////////////////////////////////////////////////////
#define MAP_OK                  13014
#define MAP_NG                  13015


//////////////////////////////////////////////////////////////////////////////
//          Ｎ　　　　　（１４０００番台）
//////////////////////////////////////////////////////////////////////////////
#define NOT_KANAKAN             14050


//////////////////////////////////////////////////////////////////////////////
//          Ｏ　　　　　（１５０００番台）
//////////////////////////////////////////////////////////////////////////////
#define OK_NOMAP                    15002
#define OFFLINE                     15003
#define ONLINE                      15004
#define ONETOUCHTIMEOUT             15005       //98/03/27 レイク


//////////////////////////////////////////////////////////////////////////////
//          Ｐ　　　　　（１６０００番台）
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
//          Ｑ　　　　　（１７０００番台）
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
//          Ｒ　　　　　（１８０００番台）
//////////////////////////////////////////////////////////////////////////////
// RAS_????????は、RASタスク予约

#define REN                         18000


//////////////////////////////////////////////////////////////////////////////
//          Ｓ　　　　　（１９０００番台）
//////////////////////////////////////////////////////////////////////////////
#define SERVER_MAIN                 19000
#define SERVER_SUB                  19001
#define SERVER_SECOND               19002

#define SEND_OK                     19003
#define SEND_NG                     19004
#define SELECT_ON                   19005
#define SELECT_OFF                  19006           //
#define SEIGYOBUF_NG                19010
#define SEND_BUSY                   19011
//（情报取得返り值）
//システム制御タスク

#define SYS_DENDAN                  19401
#define SYS_JUNBIKAN                19402

#define SYS_ONLINE_ST               19500
#define SYS_OFFLINE_ST              19501
#define SYS_ERR_ST                  19502
#define SYS_UTL_ST                  19503
#define SYS_IPPOU_ST                19504
#define SYS_TENKEN_ST               19505

#define SYS_RMN_UPDATE              19511
#define SYS_HOST_LINE               19512
#define SYS_GAIBU_LINE              19513
#define SYS_INST_LINE               19514

#define SYS_OPEN_REQ                19516
#define SYS_CLOSE_REQ               19517

#define SYS_DOOR                    19521
#define SYS_KEY                     19522
#define SYS_KAI                     19523
#define SYS_HENKYAKU                19524
#define SYS_KAISYU                  19525
#define SYS_RESET                   19526
#define SYS_HEI                     19527
#define SYS_SEISA                   19528
#define SYS_BSEISA_STS              19529
#define SYS_IPPOU_STS               19530
#define SYS_SHU_STS_OP              19531
#define SYS_JNL_STS                 19532
#define SYS_BCSOUTEN_STS_OP         19533
#define SYS_BCKAISYU_STS_OP         19534
#define SYS_BCSEISA_STS_OP          19535
#define SYS_MODE_STS                19536
#define SYS_UNIT_STS                19537

#define SYS_F_DOOR                  19540
#define SYS_R_DOOR                  19541
#define SYS_BACKUP                  19542
#define SYS_ADC                     19543
#define SYS_FUKIHATSU_LOAD          19544
#define SYS_SPARE                   19545
#define SYS_S_DOOR                  19546
#define SYS_SAFE                    19547           //CST00001
#define SYS_F_PNL                   19548           //CST00001
#define SYS_LR_DOOR                 19549           //CST30058
#define SYUURYOU                    19550

#define SYS_SHU_CHK                 19551
#define SYS_SHU_CHK_OP              19552
#define SYS_JNL_CHK                 19553
#define SYS_JNL_CHK_OP              19554
#define SYS_BSOUTEN_CHK             19555
#define SYS_BSOUTEN_CHK_OP          19556
#define SYS_CSOUTEN_CHK             19557
#define SYS_CSOUTEN_CHK_OP          19558
#define SYS_BCSOUTEN_CHK            19559
#define SYS_BCSOUTEN_CHK_OP         19560
#define SYS_BKAISYU_CHK             19561
#define SYS_BKAISYU_CHK_OP          19562
#define SYS_CKAISYU_CHK             19563
#define SYS_CKAISYU_CHK_OP          19564
#define SYS_BCKAISYU_CHK            19565
#define SYS_BCKAISYU_CHK_OP         19566
#define SYS_BSEISA_CHK              19567
#define SYS_BSEISA_CHK_OP           19568
#define SYS_CSEISA_CHK              19569
#define SYS_CSEISA_CHK_OP           19570
#define SYS_BCSEISA_CHK             19571
#define SYS_BCSEISA_CHK_OP          19572
#define SYS_SEISMIC                 19573           //GV101028
#define SYS_HEAT                    19574           //GV101028

/* 集计タスクエラ－（１９６００から）        */

/* JNLタスク·明细票タスクサホ°—ト状况取得(合计·小计印字用)（１９８００から）*/
#define SUP_FURITORI                19800
#define SUP_COMUNIT                 19801
#define SUP_GENFURI                 19802
#define SUP_FURIKOMI                19803



//////////////////////////////////////////////////////////////////////////////
//          Ｔ　　　　　（２００００番台）
//////////////////////////////////////////////////////////////////////////////
#define TBL_OK                      20000
#define TBL_NG                      20001

//　ＨＳＯＰＬ使用
#define TOR_PIDDATA                 20023


//　ＨＳＯＰＬ使用
#define TOR_ANSYO                   20035



//　ＢＳＭＴＰ　使用
//
#define TIMEOUT                     20400
#define T_KYOKA                         1
#define T_KINSI                         0

// BSCCD 使用
//


// 媒体返却可否
#define ABLE                            1
#define FUKA                          0

// 纸币放出前／后
#define MAE                           1
#define ATO                           2

// 振入方法
#define TOUKOU                        0x30
#define BANGOU                        0x31
#define KOBETSU                       0x32
#define FURIMC                        0x33

// ＡＰモ－ド
#define HEIKYOKUCYUU                  1
#define UNYOU                         2
//#define KAIKYOKU                      3        // 开局处理中
#define KYAKUMACHI                    4
#define TORIHIKI                      5
#define ENDTORIHIKI                   6
#define KAIKYOKUHOST                  7
#define IPPOUMSG                      8

// ＡＰ取引进行状态
#define INKEY                         1
#define OUTMESSAGE                    2
#define CATCHBAITAI                   3

// 许可拒否

#define KYOHI                         2

// 通帐取汲状态
#define FUKAKUTEI                     1
#define KAKUTEI                       2

// する／しない
// 振入カ－ド发行选择
#define SURU                       0x31
#define SHINAI                     0x30

// 预金种目
#define FUTSUUYOKIN                0x31
#define TOUZAYOKIN                 0x32
#define CYOCHIKUYOKIN              0x33

// 无人モ－ド情报
#define MUJIN                         1
#define YUUJIN                        2

// 电信文书选择
#define DENSIN                        1
#define BUNSYO                        2

// 取汲い状态
#define OK                            1
#define STOP                          0

// 自动补充回收モ－ドの１バイト目（纸币自动补充／回收）
#define MANHOJYU                      1
#define SENHOJYU                      2
//#define BRMKAISYU                     3        //
#define HOJYUNASHI                    4        //

// 前／后面型式情报
#define FRONT                        2
#define KOUMEN                        1

// 保留／回收
#define KOCHUHORYUU                0x01
#define KOCHUKAISHUU               0x02

// 预金种目
#define FUTSUUYOKIN                0x31
#define TOUZAYOKIN                 0x32
#define CYOCHIKUYOKIN              0x33

// 发行用振入カ－ド要补充
#define NEEDSUPPLY                      6
#define OK                            1

// ジャ－ナル用纸状态
// 明细票用纸状态
// カ－ドホッパ状态
#define EXIST                           1
#define REMAININSUFFICIENT                     5
#define NEEDSUPPLY                      6


// 振入入力タイプ
#define TOUKOU                     0x30
#define BANGOU                     0x31
#define KOBETSU                    0x32
#define FURIMC                     0x33

// 当该取引通帐许可休止
// 当该取引硬货许可休止
#define PERMIT                       OFF
#define HALT2                      ON

// 当该取引硬货许可休止
#define SHINKEN                       0
#define MOGIKEN                       1

// スピ－カ音量指定　（　体）
#define TJ_SPVOL0                     0
#define TJ_SPVOL1                     1        //
#define TJ_SPVOL2                     2        //
#define TJ_SPVOL3                     3        //
#define TJ_SPVOL4                     4        //
#define TJ_SPVOL5                     5        //
#define TJ_SPVOL6                     6        //
#define TJ_SPVOL7                     7

// クリック音时间　　（　体）
#define TJ_CLTIM0                     0
#define TJ_CLTIM1                     1        //
#define TJ_CLTIM2                     2        //
#define TJ_CLTIM3                     3

// クリック音周波数　（　体）
#define TJ_CLHRZ0                     0
#define TJ_CLHRZ1                     1        //
#define TJ_CLHRZ2                     2        //
#define TJ_CLHRZ3                     3

// 当该取引硬货许可休止
#define SHINKEN                       0
#define MOGIKEN                       1


// 振入方法
#define TOUKOU                        0x30
#define BANGOU                        0x31
#define KOBETSU                       0x32
#define FURIMC                        0x33

// 预金种目
#define FUTSUUYOKIN                0x31
#define TOUZAYOKIN                 0x32
#define CYOCHIKUYOKIN              0x33
//
#define STOP                          0        //
// 自动补充回收モ－ドの１バイト目（纸币自动补充／回收）
#define MANHOJYU                      1        //
#define SENHOJYU                      2        //
//#define BRMKAISYU                     3        //
#define HOJYUNASHI                    4        //

// 保留／回收
#define KOCHUHORYUU                0x01
#define KOCHUKAISHUU               0x02

//取引进行状态情报
#define SYOKAI                    15
#define PAYMENT                     16
#define DEPOSIT                     17
#define KICYO                     18
#define JIKKOU                    19
#define TORIKESHI                 20
#define KEIZOKU                   21
#define NONAME                     0

// 设定デ－タ
#define SOUGOUKOUZAPB              3
#define TSUMITATETEIKIPB           9
#define TEIKIYOKINPB               8
#define FUTSUUYOKINPB              14// 普通预金通帐     95.08.01  YBK     杉浦
#define NYUUKINSENYOUPB            15// 入金专用通帐     95.08.01  YBK     杉浦
#define NOUZEIJYUNBIPB             11// 纳税准备预金通帐   95.08.01  YBK     杉浦
#define TOUZAKANJYOUPB             5
#define KOUINPB                    13// 从业员通帐          95.08.01  YBK     杉浦
#define CARDLOANPB                 12// カ－ドロ－ン通帐   95.08.01  YBK     杉浦
#define SOUGOUKOUZABESSATUPB       16// 总合口座别册通帐   95.08.01  YBK     杉浦
#define TEIKITSUMIKINPB            10// 定期积金通帐     95.08.01  YBK     杉浦
#define CHOCHIKUYOKINPB            7
#define TSUUCHIYOKINPB             6
#define TESTPB                     0


// ＩＣチップ种别                                           //ICCard-CSTV4
                                                            //ICCard-CSTV4
#define IC_ICCARD           1     //ＩＣカ－ド              //ICCard-CSTV4
#define IC_SIMCARD          2     //ＳＩＭカ－ド            //ICCard-CSTV4

// ＩＣチップリセット种别                                   //ICCard-CSTV4
                                                            //ICCard-CSTV4
#define IC_WARMRESET        1     //ウォ－ムリセット        //ICCard-CSTV4
#define IC_COLDRESET        2     //コ－ルドリセット        //ICCard-CSTV4

// ＩＣチップ状态                                           //ICCard-CSTV4
                                                            //ICCard-CSTV4
#define IC_OPEN             1     //活性化状态              //ICCard-CSTV4
#define IC_NOTREADY         2     //非活性化状态            //ICCard-CSTV4
#define IC_NOTSUPP          3     //未搭载                  //ICCard-CSTV4


//////////////////////////////////////////////////////////////////////////////
//          Ｕ　　　　　（２１０００番台）
//////////////////////////////////////////////////////////////////////////////

#define UNIT_SHU                    21100
#define UNIT_PBM                    21101
#define UNIT_JPR                    21102
#define UNIT_BRM                    21103
#define UNIT_COM                    21104
#define UNIT_IMP                    21105 //99/09/22 三和
#define UNIT_PBS                    21106 //99/11/26 TMBP 东京三菱ＡＰＩＭ
#define UNIT_SPR                    21107                           //GST10020
#define UNIT_MCU                    21108                           //GST10020
#define UNIT_bcr                    21109                           //GST10020


//////////////////////////////////////////////////////////////////////////////
//          Ｖ　　　　　（２２０００番台）
//////////////////////////////////////////////////////////////////////////////
#define VRT_PROGRAM                 22000
#define VRT_BIF                     22001
#define VRT_GAMEN                   22002 // 画面バ－ジョン印字 97/02/06 山形
#define VRT_USER                    22003 // ユ－ザファイルバ－ジョン印字 99/03/01 野村

//音声制御、ＯＰＬ画面操作
#define VG_VGEND                    22100

//////////////////////////////////////////////////////////////////////////////
//          Ｗ　　　　　（２３０００番台）
//////////////////////////////////////////////////////////////////////////////
#define WFS_CDM_MIX_MINIMUM_NUMBER_OF_BILLS_LESS    0x7FFF  //for CEN/XFS MIX_NUMBER(残量内出金) ICB50036
//////////////////////////////////////////////////////////////////////////////
//          Ｘ　　　　　（２４０００番台）
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
//          Ｙ　　　　　（２５０００番台）
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
//          Ｚ　　　　　（２６０００番台）
//////////////////////////////////////////////////////////////////////////////

#define HT2845AE        1   //壁面ＡＴＭ        PG#00007
#define HT2845          0   //普通ＡＴＭ        PG#00007
#define HT2845V         2   //45V               CST70020
#define CZ5000          3   //                  GST10003
#define ADM1            4   //                  GST10003
#define ADM2            5   //                  GST10003
#define EXCD1           6   //                  GST10003
#define EXCD3           7   //                  GST10003
#define OTHER_TYPE      8   //                  GST10003
#define HT2845W         9   //                  13-00-07-04
#define TSEA45          10  //                  STD00029(PG#00120)


#define SPL_KEY_OPEN                0x5001  // 开局                             //CST70014
#define SPL_KEY_CLOSE               0x5002  //                                  //CST70014
#define SPL_KEY_OPEN_NG             0x5003  // 开局取消                         //CST70014
#define SPL_KEY_RESET               0x4108  // リセット                         //CST70014
#define SPL_KEY_PROGRAM_LOAD        0x41B2  // プログラムロ－ドボタン           //CST70014
#define SPL_KEY_PROGRAM_LOAD_NG     0x5005  // プログラムロ－ド取消キ－         //CST70014
#define SPL_KEY_UNYOU_KAISHIBI_HENKOU   0x41BC  // 运用开始日变更ボタン         //CST70014
#define SPL_KEY_UNYOU_KAISHIBI_SETTEI   0x41BD  // 运用开始日设定ボタン         //CST70014
#define SPL_KEY_USER_LOAD           0x41BE  // ユ—サ＂ファイルロ—ト＂ホ＂タン //CST70014
#define SPL_KEY_USER_LOAD_NG        0x5016  // ユ—サ＂ファイルロ—ト＂中止     //CST70014
#define SPL_KEY_MAITENANCE_START    0x5010  // 保守开始                         //CST70014
#define SPL_KEY_MAITENANCE_END      0x5011  // 保守终了                         //CST70014
#define SPL_KEY_TANTAI              0x5013  // 单体テスト开始                   //CST70014
#define SPL_KEY_OPERATOR            0x0005  // 系员处理                         //CST70014
#define SPL_KEY_POWOFF              0x5006  // 电源断キ－                       //CST70014
#define SPL_KEY_JNLFILEEXPORT           0X41DD  //電子ジャーナル吸上げボタン    //CST70014
#define SPL_KEY_JNLFILEEXPORT_NG        0x41F0  //ICB40025 JNL OUT END          //CST70014
#define SPL_KEY_JNLFILEEXPORT_ERROR     0x41F1  //ICB40025 JNL OUT ERROR        //CST70014
#define SPL_KEY_SHOUKEI                 0x4120  // 小计ボタン                   //CST70014
#define SPL_KEY_GOUKEI                  0x4121  // 合计ボタン                   //CST70014
#define SPL_KEY_SETTEINAIYOU_INJI       0x4162  // 设定内容を印字ボタン         //CST70014
#define SPL_KEY_JNLKENSAKU_RESULTINJI   0x4199  // 明细表に印字ボタン           //CST70014
#define SPL_KEY_PROGRAMREV_INJI         0x41B3  // プログラムレビジョンボタン   //CST70014
#define SPL_KEY_SHIHEISOUTENSETTEI      0x4222  // 纸币装填设定キ－     HQY     //CST70014
#define SPL_KEY_SHIHEISOUTENSHOUKAI_INJI    0x4224  // 纸币装填照会印字キ－     //CST70014
#define SPL_KEY_IMAGE_DEL_CONFIRM   0x4229  //イメージ消去確認ボタン            //CST70014
#define SPL_KEY_JNLINJI_OK_NG       0x4230  //日志休止                          //CST70014
#define SPL_KEY_AKEY                0x4225  //密钥A                             //CST70456
#define SPL_KEY_BKEY                0x4226  //密钥B                             //CST70456
#define SPL_KEY_MASTERKEY           0x4227  //主密钥                            //CST70456
#define SPL_KEY_PARAFILEDEL_CONFIRM 0x422B  //delete parameter file             //ICB62003
#define SPL_KEY_HOSTIP              0x422C  //Set Host IP Info                  //ICB62503
#define SPL_KEY_ATMLAN1             0x422D  //Set ATM LAN1 Info                 //ICB62503
#define SPL_KEY_ATMLAN2             0x422E  //Set ATM LAN2 Info                 //ICB62503
#define SPL_KEY_MONITORSET          0x422F  //Set Monitor Com Info              //ICB62509
#define SPL_KEY_MONITORPARSET       0x4231  //Set Monitor Com Par Info          //ICB62902
#define SPL_KEY_VDM_START           0x4232  //进入VDM模式                       //GST10029
#define SPL_KEY_VDM_EXIT            0x4233  //退出VDM模式                       //GST10029
#define SPL_KEY_VDM_EXITFAIL        0x4234  //退出VDM模式失败                   //GST10029
#define SPL_KEY_SHUTDOWN            0x4235  //SPL关机                           //GST10372
#define SPL_KEY_REBOOT              0x4236  //SPL重启                           //GST10372
#define TTU_KEY_MAITENANCE_START    0x4237  //TTU维护开始                       //GV110003
#define TTU_KEY_MAITENANCE_END      0x4238  //TTU维护结束                       //GV110003
#define TTU_KEY_OPEN                0x4239  //开局                              //GV110003
#define TTU_KEY_CLOSE               0x423A  //闭局                              //GV110003
#define TTU_KEY_OPEN_NG             0x423B  //开局取消                          //GV110003
#define TTU_KEY_STATISTIC_QUERY     0x423C  //小计                              //GV110003
#define TTU_KEY_STATISTIC_CLEAR     0x423D  //合计                              //GV110003
#define TTU_KEY_CASHREPLENISHMENT   0x423E  //纸币装填设定                      //GV110003
#define TTU_KEY_CASHREMAIN_PRINT    0x423F  //纸币装填印字                      //GV110003
#define TTU_KEY_AKEY                0x4240  //密钥A设定                         //GV110003
#define TTU_KEY_BKEY                0x4241  //密钥B设定                         //GV110003
#define TTU_KEY_MASTERKEY           0x4242  //主密钥设定                        //GV110003
#define TTU_KEY_HOSTIP              0x4243  //主机IP设定                        //GV110003
#define TTU_KEY_MONITORSET          0x4244  //监视系统连接方式设定              //GV110003
#define TTU_KEY_MONITORPARSET       0x4245  //监视系统连接参数设定              //GV110003
#define TTU_KEY_PROGRAMREV_PRINT    0x4246  //程序版本打印。                    //GV110003
#define TTU_KEY_MAINTENANCEMENU_ENTER   0x4247  //维护菜单进入                  //GV110003
#define TTU_KEY_MAINTENANCEMENU_EXIT    0x4248  //维护菜单退出                  //GV110003
#define TTU_KEY_CLEAR_JNL           0x4249  //清除电子日志                      //GV110003
#define TTU_KEY_INITIALSETTING_LOAD 0x424A  //装载不挥发数据                    //GV110003
#define TTU_KEY_CANCEL_AUTO_RUN     0x424B  //取消自启动                        //GV110003
#define TTU_KEY_VRT_PRINT           0x424C  //VRT版本印字                       //GV110003
#define TTU_KEY_ATM_SETTING_ALL_PRINT   0x424D  //ATM设定全印字                 //GV110003
#define TTU_KEY_RESET               0x424E  //复位                              //GV110003
#define TTU_KEY_VDM_START           0x424F  //进入VDM模式                       //GV110003
#define TTU_KEY_VDM_EXIT            0x4250  //正常退出VDM模式                   //GV110003
#define TTU_KEY_VDM_EXITFAIL        0x4251  //退出VDM模式失败                   //GV110003
#define TTU_KEY_SHUTDOWN            0x4252  //关机                              //GV110003
#define TTU_KEY_REBOOT              0x4253  //重启                              //GV110003
#define TTU_KEY_OPERATORMENU_ENTER  0x4254  //操作员菜单进入                    //GV110003
#define TTU_KEY_QUIT_TTU            0x4255  //退出TTU到管理员处理               //GV120002

#define SPL_LST_OFF                  0                                              //CST70014
#define SPL_LST_ON                   1                                              //CST70014
#define SPL_LST_MUSHI                0xfff0                                         //CST70014

#define SPL_LAMP_ILLUST_SHU1         0x4100  // カ－ド·明细搬送路１                //CST70014
#define SPL_LAMP_ILLUST_BRM1         0x41C0  // 纸币搬送路１                        //CST70014

#define SPL_UNIT_BRM                 5   //纸币ユニット                             //CST70014

#define SPL_KAKARI_BRM_SETNG         1   //ユニットセット不良                       //CST70014
#define SPL_KAKARI_BILL_MANFULL      4   //万元满杯                                 //CST70014
#define SPL_KAKARI_BILL_SENFULL      5   //千元满杯
#define SPL_KAKARI_BSOUTENRJ_FULL    6   //装填リシ＂ェクト部满杯                   //CST70014
#define SPL_KAKARI_RJCTOP_FULL       7   //リシ＂ェクトカセット上段满杯             //CST70014
#define SPL_KAKARI_BILLC_FULL        9   //纸币カセット满杯                         //CST70014
#define SPL_KAKARI_BILL_MANHOJUU     10  //万元要补充
#define SPL_KAKARI_BILL_SENHOJUU     11  //千元要补充
#define SPL_KAKARI_BILL_MANZANSHOU   12  //万元残量少                               //CST70014
#define SPL_KAKARI_BILL_SENZANSHOU   13  //千元残量少
#define SPL_KAKARI_BRMRJC_SETNG      14  //リシ＂ェクトカセットセット不良           //CST70014
#define SPL_KAKARI_BRM_MAEHANSOURO   21  //纸币前搬送路开                           //CST70014
#define SPL_KAKARI_BRM_USHIROTOBIRA  22  //纸币后门开                               //CST70014
#define SPL_KAKARI_BILL_CASSETTE3_FULL     23  //纸币钱箱4满杯
#define SPL_KAKARI_BILL_CASSETTE3_HOJUU    24  //纸币钱箱4要补充
#define SPL_KAKARI_BILL_CASSETTE3_ZANSHOU  25  //纸币钱箱4残量少
#define SPL_STS_OPERR_SHU_NOTREADY         84  //  ＳＨＵ准备未完                   //CST70014
#define SPL_STS_POWOFF_START               93  //  电源断处理开始                   //CST70014
#define SPL_STS_OPERR_RESET_AND_RETRY      153 //  リセット后再指定通知             //CST70014
#define SPL_STS_SHU_NOTREADY_START         146 //  ＳＨＵ准备未完状态开始           //CST70014
#define SPL_STS_SHU_NOTREADY_END           147 //  ＳＨＵ准备未完状态终了           //CST70014
#define SPL_STS_INITERR                         94  //  イニシャルエラ－立ちあげ异常

#define FW_STD                  0           // 標準                                 //CIF00001


#define RECEIVE_WAIT            0        //排出并等待受取                       //CST70036
#define RECEIVE_NO_WAIT         1        //只排出不等待受取                     //CST70036

//------------------------------------------------------------------------------
//      有偿部品ＩＤ
//------------------------------------------------------------------------------
#define  HOS_YUUSHOU_OPLLCD         0       // 液晶ディスプレイ（ＯＰＬ）
#define  HOS_YUUSHOU_SPLLCD         1       // 液晶ディスプレイ（ＳＰＬ）
#define  HOS_YUUSHOU_MSHEAD         2       // ＭＳヘッド（ＰＢＭ）
#define  HOS_YUUSHOU_MCHEAD         3       // ＭＣヘッド（ＭＣＵ）
#define  HOS_YUUSHOU_PBMHEAD        4       // 印字ヘッド（ＰＢＭ）
#define  HOS_YUUSHOU_SPRHEAD        5       // 印字ヘッド（ＳＰＲ）
#define  HOS_YUUSHOU_JPR1HEAD       6       // 印字ヘッド（ＪＮＬメカ１）
#define  HOS_YUUSHOU_JPR2HEAD       7       // 印字ヘッド（ＪＮＬメカ２）
#define  HOS_YUUSHOU_FDD            8       // ＦＤＤ
#define  HOS_YUUSHOU_HDD            9       // ＨＤＤ
#define  HOS_YUUSHOU_BATTERY        10      // 停电用バッテリ－
#define  HOS_YUUSHOU_CDROM          11      // ＣＤ-ＲＯＭドライブ
#define  HOS_YUUSHOU_HEATER         12      // クリ－ンユニットヒ－トランプ
#define  HOS_YUUSHOU_TEMPSENSOR     13      // クリ－ンユニット温度检知センサ
#define  HOS_YUUSHOU_PBMRIBBON      14      // 通帐印字リボン
#define  HOS_YUUSHOU_SPRCUTTER      15      // 明细票カッタモ－タ(ＳＰＲ）
#define  HOS_YUUSHOU_COMBELT        16      // 硬货搬送ベルト(ＣＯＭ)
#define  HOS_YUUSHOU_IMPRHEAD1      17      // 印字ヘッド（ＩＭＰＲ） 99/10/28 三和
#define  HOS_YUUSHOU_IMPRSTAMP      18      // 出纳印（ＩＭＰＲ） 99/10/28 三和
#define  HOS_YUUSHOU_IMPRROLLER     19      // 插入口幅寄せロ－ラ（ＩＭＰＲ） 99/10/28 三和
#define  HOS_YUUSHOU_IMPRRIBON1     20      // ＩＭＰＲ印字リボン 99/10/28 三和
#define  HOS_YUUSHOU_IMPRSTAMPINK   21      // 出纳印インク 99/10/28 三和
#define  HOS_YUUSHOU_HONTAIDENGEN   22      // 本体电源 2000/01/21 ＭＲ－ＡＴＭ
#define  HOS_YUUSHOU_BRMDENGEN      23      // ＢＲＭ电源 2000/01/21 ＭＲ－ＡＴＭ
#define  HOS_YUUSHOU_PAGEGAEROLLER  24      // ペ－ジ替えロ－ラ 2000/01/21 ＡＰＩＭ
#define  HOS_YUUSHOU_HANSOUROLLER   25      // 搬送ロ－ラ 2000/01/21 ＡＰＩＭ
#define  HOS_YUUSHOU_LCDFAN         26      // ＬＣＤ ＦＡＮ            //CST30049
#define  HOS_YUUSHOU_CEFAN          27  // ＣＥ ＦＡＮ          //CST30049
#define  HOS_YUUSHOU_UPFAN          28  // ＵＰ ＦＡＮ          //CST30049
#define  HOS_YUUSHOU_DCCONVERT      29  // ＤＣ / ＤＣ コンバータ       //CST30049
#define  HOS_YUUSHOU_BCFAN          30  // ＢＣ ＦＡＮ          //CST30049
#define  HOS_YUUSHOU_WBCBCUNIT      31  // 鑑別 ユニット        //CST30049
#define  HOS_YUUSHOU_WCSCSM         32  // ＣＳＭシートローラＡ、Ｂ //CST30049
#define  HOS_YUUSHOU_WCSCASSETTE1ROLR   33  // カセット１シートローラＡ、Ｂ //CST30049
#define  HOS_YUUSHOU_WRBCASSETTE2ROLR   34  // カセット２シートローラＡ、Ｂ //CST30049
#define  HOS_YUUSHOU_WRBCASSETTE3ROLR   35  // カセット３シートローラＡ、Ｂ //CST30049
#define  HOS_YUUSHOU_CARRYWAYOPEN   36  // 搬送路オープン       //CST30049
#define  HOS_YUUSHOU_WTSREEL        37  // テ－ブリール         //CST30049
#define  HOS_YUUSHOU_WCSCSMUNIT     38  // ＣＳＭ ユニット      //CST30049
#define  HOS_YUUSHOU_WRBCASSETTE2   39  // カセット２           //CST30049
#define  HOS_YUUSHOU_WRBCASSETTE3   40  // カセット３           //CST30049
#define  HOS_YUUSHOU_WRBCASSETTE4ROLR   41  // カセット4シートローラＡ、Ｂ  //03-00-07-03
#define  HOS_YUUSHOU_WRBCASSETTE4   42  // カセット4                //03-00-07-03
#define  HOS_YUUSHOU_SAFEFAN        43  // SAFE FAN             //03-00-07-03
#define  HOS_YUUSHOU_BOX2PICKUPROLA 44  //カセット2 ピックアップローラA  //03-00-07-03
#define  HOS_YUUSHOU_BOX3PICKUPROLA 45  //カセット３ ピックアップローラA //03-00-07-03
#define  HOS_YUUSHOU_BOX4PICKUPROLA 46  //カセット４ ピックアップローラA //03-00-07-03
#define  HOS_YUUSHOU_CSMPICKUPROLAA 47  //CSMピックアップローラA //03-00-07-03
#define  HOS_YUUSHOU_CSMPICKUPROLAB 48  //CSMピックアップローラB    //03-00-07-03
#define  HOS_YUUSHOU_UPFAN2         49  //ＵＰ ＦＡＮ 2 //13-00-07-04
#define  HOS_YUUSHOU_PCFAN          50  //ＰＣ ＦＡＮ   //13-00-07-04
#define  HOS_YUUSHOU_WRBCASSETTE5ROLR   51  //カセット５シートローラＡ、Ｂ  //13-00-07-04
#define  HOS_YUUSHOU_WRBCASSETTE5   52  //カセット５                        //13-00-07-04
#define  HOS_YUUSHOU_BOX5PICKUPROLA 53  //カセット５ピックアップローラA     //13-00-07-04
#define  HOS_YUUSHOU_MABROLR        54  //MAB シートローラ                  //13-00-07-04
#define  HOS_YUUSHOU_URJBROLR       55  //URJB シートローラ                 //13-00-07-04

//#endif
